libtr: tr::ArrayColorTexture2D Class Reference
tr::ArrayColorTexture2D Class Reference
System » Graphics » Textures
Two-dimensional array color texture.
Public Member Functions
ArrayColorTexture2D (glm::ivec2 size, int layers, bool mipmapped=false, ColorTextureFormat format=ColorTextureFormat::RGBA8)
Allocates an uninitialized 2D array color texture.
ArrayColorTexture2D (std::span< SubBitmap > layers, bool mipmapped=false, ColorTextureFormat format=ColorTextureFormat::RGBA8)
Constructs a 2D array color texture with data uploaded from a list of bitmaps.
glm::ivec2 size () const noexcept
Gets the size of the texture.
int layers () const noexcept
Gets the number of layers in the texture.
void clearRegion (const RectI3 &rect, const RGBAF &color) noexcept
Clears a region of the texture.
void copyRegion (const glm::ivec3 &offset, const ArrayColorTexture2D &src, const RectI3 &rect) noexcept
Copies a region from another texture.
void setLayerRegion (int layer, glm::ivec2 tl, SubBitmap bitmap) noexcept
Sets a region of a layer.
Public Member Functions inherited from tr::ColorTexture
void setSwizzle (Swizzle r, Swizzle g, Swizzle b, Swizzle a) noexcept
Sets the swizzle parameters of the texture.
void setBorderColor (RGBAF color) noexcept
Sets the border color of the texture sampler (used when Wrap::BORDER_CLAMP is in use).
void clear (const RGBAF &color) noexcept
Clears the texture.
Public Member Functions inherited from tr::Texture
void setMinFilter (MinFilter filter) noexcept
Sets the minifying filter used by the texture sampler.
void setMagFilter (MagFilter filter) noexcept
Sets the magnifying filter used by the texture sampler.
void setWrap (Wrap wrap) noexcept
Sets the wrapping used for by the texture sampler.
void setLabel (std::string_view label) noexcept
Sets the debug label of the texture.
Detailed Description
Two-dimensional array color texture.
Constructor & Destructor Documentation
ArrayColorTexture2D() [1/2]
tr::ArrayColorTexture2D::ArrayColorTexture2D (glm::ivec2 size, int layers, bool mipmapped = false, ColorTextureFormat format = ColorTextureFormat::RGBA8)
Allocates an uninitialized 2D array color texture.
Exception Safety
Strong exception guarantee.
Exceptions
TextureBadAlloc If allocating the texture fails.
Parameters
[in] size The size of the texture in texels.
[in] layers The number of layers in the texture.
[in] mipmapped Whether the texture will be mipmapped.
[in] format The internal format of the texture.
Referenced by copyRegion().
ArrayColorTexture2D() [2/2]
tr::ArrayColorTexture2D::ArrayColorTexture2D (std::span< SubBitmap > layers, bool mipmapped = false, ColorTextureFormat format = ColorTextureFormat::RGBA8)
Constructs a 2D array color texture with data uploaded from a list of bitmaps.
Exception Safety
Strong exception guarantee.
Exceptions
TextureBadAlloc If allocating the texture fails.
Parameters
[in] layers
The layer bitmaps.
Precondition
layers cannot be empty, and the bitmaps must all be of the same size.
Parameters
[in] mipmapped Whether the texture will be mipmapped.
[in] format The internal format of the texture.
Member Function Documentation
size()
glm::ivec2 tr::ArrayColorTexture2D::size () const noexcept
Gets the size of the texture.
Returns
The size of the texture in texels.
Referenced by ArrayColorTexture2D().
layers()
int tr::ArrayColorTexture2D::layers () const noexcept
Gets the number of layers in the texture.
Returns
The number of layers in the texture.
Referenced by ArrayColorTexture2D(), ArrayColorTexture2D(), and layers().
clearRegion()
void tr::ArrayColorTexture2D::clearRegion (const RectI3 & rect, const RGBAF & color) noexcept
Clears a region of the texture.
Precondition
The region must fully be inside the bounds of the texture.
Parameters
[in] rect The region to clear (layers are treated as the Z coordinate).
[in] color The color to clear the region to.
Referenced by clearRegion().
copyRegion()
void tr::ArrayColorTexture2D::copyRegion (const glm::ivec3 & offset, const ArrayColorTexture2D & src, const RectI3 & rect) noexcept
Copies a region from another texture.
Precondition
The region must fully be inside the bounds of the texture.
Parameters
[in] offset The offset within the texture (layers are treated as the Z coordinate).
[in] src The texture to copy from.
[in] rect The bounds of the copied region within the source texture (layers are treated as the Z coordinate).
Referenced by copyRegion().
setLayerRegion()
void tr::ArrayColorTexture2D::setLayerRegion (int layer, glm::ivec2 tl, SubBitmap bitmap) noexcept
Sets a region of a layer.
Precondition
The region must fully be inside the bounds of the texture.
Parameters
[in] layer The layer whose region to set.
[in] tl The top-left corner of the region within the layer.
[in] bitmap The bitmap data to set the region to.
Referenced by setLayerRegion().