libtr: tr::SubBitmap::Iterator Class Reference
tr::SubBitmap::Iterator Class Reference
System » Bitmaps
Immutable bitmap pixel iterator.
Public Types
using value_type = PixelRef
RandomAccessIterator typedef requirement.
using pointer = const value_type*
RandomAccessIterator typedef requirement.
using difference_type = int
RandomAccessIterator typedef requirement.
Public Member Functions
Iterator () noexcept=default
Default-constructs an iterator.
Iterator (SubBitmap bitmap, glm::ivec2 pos) noexcept
Constructs an iterator to a bitmap pixel.
std::partial_ordering operator<=> (const Iterator &) const noexcept
Three-way comparison operator.
bool operator== (const Iterator &) const noexcept
Equality comparison operator.
value_type operator* () const noexcept
Dereferences the iterator.
value_type operator[] (difference_type diff) const noexcept
Dereferences the iterator with a subscript.
value_type operator[] (glm::ivec2 diff) const noexcept
Dereferences the iterator with a subscript.
pointer operator-> () const noexcept
Dereferences the iterator through a pointer.
Iterator & operator++ () noexcept
Increments the iterator.
Iterator operator++ (int) noexcept
Post-increments the iterator.
Iterator & operator+= (difference_type diff) noexcept
Advances the iterator.
Iterator & operator+= (glm::ivec2 diff) noexcept
Advances an iterator.
Iterator & operator-- () noexcept
Decrements the iterator.
Iterator operator-- (int) noexcept
Post-decrements the iterator.
Iterator & operator-= (difference_type diff) noexcept
Moves the iterator back.
Iterator & operator-= (glm::ivec2 diff) noexcept
Moves the iterator back.
Detailed Description
Immutable bitmap pixel iterator.
The iterator fulfills the RandomAccessIterator requirements.
Member Typedef Documentation
value_type
using tr::SubBitmap::Iterator::value_type = PixelRef
RandomAccessIterator typedef requirement.
pointer
using tr::SubBitmap::Iterator::pointer = const value_type*
RandomAccessIterator typedef requirement.
difference_type
using tr::SubBitmap::Iterator::difference_type = int
RandomAccessIterator typedef requirement.
Constructor & Destructor Documentation
Iterator() [1/2]
tr::SubBitmap::Iterator::Iterator () default noexcept
Default-constructs an iterator.
An iterator constructed in this manner is in an non-dereferencable state until a valid value is assigned to it.
Referenced by Iterator(), operator+, operator+, operator+, operator+, operator++(), operator++(), operator+=(), operator+=(), operator-, operator-, operator-, operator-, operator-, operator--(), operator--(), operator-=(), operator-=(), operator<=>(), and operator==().
Iterator() [2/2]
tr::SubBitmap::Iterator::Iterator (SubBitmap bitmap, glm::ivec2 pos) noexcept
Constructs an iterator to a bitmap pixel.
Parameters
[in] bitmap The sub-bitmap.
[in] pos The position of the pixel within the sub-bitmap.
Member Function Documentation
operator<=>()
std::partial_ordering tr::SubBitmap::Iterator::operator<=> (const Iterator &) const noexcept
Three-way comparison operator.
operator==()
bool tr::SubBitmap::Iterator::operator== (const Iterator &) const noexcept
Equality comparison operator.
operator*()
value_type tr::SubBitmap::Iterator::operator* () const noexcept
Dereferences the iterator.
Returns
The pixel reference.
operator[]() [1/2]
value_type tr::SubBitmap::Iterator::operator[] (difference_type diff) const noexcept
Dereferences the iterator with a subscript.
Parameters
[in] diff The pixel relative to the iterator to access.
Returns
The pixel reference.
operator[]() [2/2]
value_type tr::SubBitmap::Iterator::operator[] (glm::ivec2 diff) const noexcept
Dereferences the iterator with a subscript.
Parameters
[in] diff The pixel relative to the iterator to access (in vector form).
Returns
The pixel reference.
operator->()
pointer tr::SubBitmap::Iterator::operator-> () const noexcept
Dereferences the iterator through a pointer.
Returns
A pointer to the pixel reference.
operator++() [1/2]
Iterator & tr::SubBitmap::Iterator::operator++ () noexcept
Increments the iterator.
Returns
A reference to the iterator.
operator++() [2/2]
Iterator tr::SubBitmap::Iterator::operator++ (int) noexcept
Post-increments the iterator.
Returns
An iterator with the prior state of the incremented iterator.
operator+=() [1/2]
Iterator & tr::SubBitmap::Iterator::operator+= (difference_type diff) noexcept
Advances the iterator.
Parameters
[in] diff The number of pixels to move forward.
Returns
A reference to the iterator.
operator+=() [2/2]
Iterator & tr::SubBitmap::Iterator::operator+= (glm::ivec2 diff) noexcept
Advances an iterator.
Parameters
[in] diff The number of pixels to move forward (in vector form).
Returns
A reference to the iterator.
operator--() [1/2]
Iterator & tr::SubBitmap::Iterator::operator-- () noexcept
Decrements the iterator.
Returns
A reference to the iterator.
operator--() [2/2]
Iterator tr::SubBitmap::Iterator::operator-- (int) noexcept
Post-decrements the iterator.
Returns
An iterator with the prior state of the decremented iterator.
operator-=() [1/2]
Iterator & tr::SubBitmap::Iterator::operator-= (difference_type diff) noexcept
Moves the iterator back.
Parameters
[in] diff The number of pixels to move backward.
Returns
A reference to the iterator.
operator-=() [2/2]
Iterator & tr::SubBitmap::Iterator::operator-= (glm::ivec2 diff) noexcept
Moves the iterator back.
Parameters
[in] diff The number of pixels to move backward (in vector form).
Returns
A reference to the iterator.