libtr: tr::FileError Class Reference
tr::FileError Class Reference abstract
Miscellaneous » Streams
Generic file error base exception type.
Public Member Functions
FileError (const char *path) noexcept
Constructs a file error with a path string.
FileError (std::string path) noexcept
Constructs a file error with a path string.
FileError (const std::filesystem::path &path)
Constructs a file error with a path.
const char * what () const noexcept override=0
Pure virtual what() function.
const std::string & path () const noexcept
Gets the path string.
Detailed Description
Generic file error base exception type.
Cannot be thrown directly as what() is a pure virtual function.
Constructor & Destructor Documentation
FileError() [1/3]
tr::FileError::FileError (const char * path) noexcept
Constructs a file error with a path string.
Parameters
[in] path A path string.
FileError() [2/3]
tr::FileError::FileError (std::string path) noexcept
Constructs a file error with a path string.
Parameters
[in] path A path string.
FileError() [3/3]
tr::FileError::FileError (const std::filesystem::path & path)
Constructs a file error with a path.
Parameters
[in] path A filesystem path.
Exceptions
std::bad_alloc If copying the string fails.
Member Function Documentation
what()
const char * tr::FileError::what () const override pure virtual noexcept
Pure virtual what() function.
Implemented in tr::BitmapLoadError, tr::BitmapSaveError, tr::FileNotFound, tr::FileOpenError, tr::ShaderLoadError, tr::TTFontLoadError, and tr::UnsupportedAudioFile.
path()
const std::string & tr::FileError::path () const noexcept
Gets the path string.
Returns
A reference to the path string.
Referenced by FileError(), FileError(), FileError(), and path().