libtr: tr::Window Class Reference
tr::Window Class Reference
System » Window
The main application window.
Public Member Functions
Window (const char *title, glm::ivec2 size, glm::ivec2 pos=CENTERED_POS, WindowFlag flags=WindowFlag::DEFAULT, const GraphicsProperties &gfxProperties={})
Opens a window.
const char * title () const noexcept
Gets the title of the window.
void setTitle (const char *title) noexcept
Sets the title of the window.
void setTitle (const std::string &title) noexcept
Sets the title of the window.
void setIcon (const Bitmap &bitmap) noexcept
Sets the icon of the window.
void setIcon (const BitmapView &view) noexcept
Sets the icon of the window.
glm::ivec2 size () const noexcept
Gets the size of the window.
void setSize (glm::ivec2 size) noexcept
Sets the size of the window.
std::optional< DisplayMode > fullscreenMode () const noexcept
Gets the window's fullscreen display mode.
void setFullscreenMode (const DisplayMode &dmode)
Sets the window's fullscreen display mode.
WindowMode windowMode () const noexcept
Gets the window's window mode.
void setWindowMode (WindowMode mode)
Sets the window's window mode.
bool resizable () const noexcept
Gets whether the window is resizable.
void setResizable (bool resizable) noexcept
Sets whether the window is resizable.
glm::ivec2 minSize () const noexcept
Gets the minimum resizable size of the window.
void setMinSize (glm::ivec2 minSize) noexcept
Sets the minimum resizable size of the window.
glm::ivec2 maxSize () const noexcept
Gets the maximum resizable size of the window.
void setMaxSize (glm::ivec2 maxSize) noexcept
Sets the maximum resizable size of the window.
glm::ivec2 position () const noexcept
Gets the position of the window relative to the top-left corner of the display.
void setPosition (glm::ivec2 pos) noexcept
Sets the position of the window relative to the top-left corner of the display.
bool bordered () const noexcept
Gets whether the window is bordered.
void setBordered (bool bordered) noexcept
Sets whether the mouse is bordered.
bool shown () const noexcept
Gets whether the window is being shown.
void show () noexcept
Unhides the window.
void hide () noexcept
Hides the window.
bool maximized () const noexcept
Gets whether the window is maximized.
void maximize () noexcept
Maximizes the window.
void restore () noexcept
Restores the window back to its previous size.
bool minimized () const noexcept
Gets whether the window is minimized.
void minimize () noexcept
Minimizes the window.
bool hasFocus () const noexcept
Gets whether the window has input focus.
void raise () noexcept
Raises the window above the rest and gives it input focus.
bool mouseGrabbed () const noexcept
Gets whether the mouse is grabbed and confined to this window.
void setMouseGrab (bool grab) noexcept
Sets whether the mouse is grabbed and confined to this window.
std::optional< RectI2 > mouseConfines () const noexcept
Gets the area the mouse is confined to when this window has focus.
void setMouseConfines (const RectI2 &rect) noexcept
Sets the area the mouse is confined to when this window has focus.
void resetMouseConfines () noexcept
Resets the area the mouse is confined to.
bool alwaysOnTop () const noexcept
Gets whether the window is always on top.
void setAlwaysOnTop (bool alwaysOnTop) noexcept
Sets whether the window is always on top.
void flash (FlashOperation operation) noexcept
Flashes the window to get the user's attention.
float opacity () const noexcept
Gets the opacity of the window.
void setOpacity (float opacity) noexcept
Sets the opacity of the window.
VSync vsync () const noexcept
Gets the window's V-sync mode.
void setVSync (VSync vsync) noexcept
Sets the window's V-sync mode.
GraphicsContext & graphics () noexcept
Gets the window's graphics context.
const GraphicsContext & graphics () const noexcept
Gets the window's graphics context.
Backbuffer & backbuffer () noexcept
Gets the window's backbuffer.
const Backbuffer & backbuffer () const noexcept
Gets the window's backbuffer.
EventQueue & events () noexcept
Gets the window's event queue.
const EventQueue & events () const noexcept
Gets the window's event queue.
const Keyboard & keyboard () const noexcept
Gets access to the keyboard.
Mouse & mouse () noexcept
Gets access to the mouse.
const Mouse & mouse () const noexcept
Gets access to the mouse.
Detailed Description
The main application window.
This class handles most of the basic functionality of the application, not just the window itself. Single instances of the EventQueue, Keyboard, Mouse and GraphicsContext classes belong to the window object.
The Window class uses something akin to the singleton pattern. It is still your job to instantiate the window once (and only once!), after which it will stay active until its destructor is called, but this instance will be globally available through window(). Reopening the window after it has been closed is a valid action.
Window is movable, but not copyable. A moved window is left in a state where another window can be moved into it, but is otherwise unusable.
Constructor & Destructor Documentation
Window()
tr::Window::Window (const char * title, glm::ivec2 size, glm::ivec2 pos = CENTERED_POS, WindowFlag flags = WindowFlag::DEFAULT, const GraphicsProperties & gfxProperties = {})
Opens a window.
Note
The window starts hidden and show() must be called.
Exception Safety
Strong exception guarantee.
Exceptions
WindowOpenError If opening the window fails.
Parameters
[in] title The title of the window.
[in] size The size of the window in pixels.
[in] pos The position of the window, offset to the top-left corner of the window in pixels. Several special sentinels exist, such as CENTERED_POS, as well as DisplayInfo::centeredPos().
[in] flags The flags of the window.
[in] gfxProperties The properties of the window's graphics context.
Member Function Documentation
title()
const char * tr::Window::title () const noexcept
Gets the title of the window.
Returns
A C-string containing the title of the window.
Referenced by Window(), setTitle(), and setTitle().
setTitle() [1/2]
void tr::Window::setTitle (const char * title) noexcept
Sets the title of the window.
Parameters
[in] title The new title of the window.
Referenced by setTitle(), and setTitle().
setTitle() [2/2]
void tr::Window::setTitle (const std::string & title) noexcept
Sets the title of the window.
Parameters
[in] title The new title of the window.
setIcon() [1/2]
void tr::Window::setIcon (const Bitmap & bitmap) noexcept
Sets the icon of the window.
Parameters
[in] bitmap The new window icon.
Referenced by setIcon(), and setIcon().
setIcon() [2/2]
void tr::Window::setIcon (const BitmapView & view) noexcept
Sets the icon of the window.
Parameters
[in] view The new window icon.
size()
glm::ivec2 tr::Window::size () const noexcept
Gets the size of the window.
Returns
The size of the window in pixels.
Referenced by Window(), setSize(), and size().
setSize()
void tr::Window::setSize (glm::ivec2 size) noexcept
Sets the size of the window.
Parameters
[in] size The new size of the window in pixels.
Referenced by setSize().
fullscreenMode()
std::optional< DisplayMode > tr::Window::fullscreenMode () const noexcept
Gets the window's fullscreen display mode.
Returns
The window's fullscreen display mode, or std::nullopt if the window isn't fullscreen.
Referenced by fullscreenMode().
setFullscreenMode()
void tr::Window::setFullscreenMode (const DisplayMode & dmode)
Sets the window's fullscreen display mode.
This function sets the window to fullscreen if it isn't already.
Exception Safety
Strong exception guarantee.
Exceptions
WindowError If setting the fullscreen mode fails.
Parameters
[in] dmode The new fullscreen mode.
Referenced by setFullscreenMode().
windowMode()
WindowMode tr::Window::windowMode () const noexcept
Gets the window's window mode.
Returns
The window's display mode.
Referenced by windowMode().
setWindowMode()
void tr::Window::setWindowMode (WindowMode mode)
Sets the window's window mode.
Exception Safety
Strong exception guarantee.
Exceptions
WindowError If setting the window mode fails.
Parameters
[in] mode The new display mode.
Referenced by setWindowMode().
resizable()
bool tr::Window::resizable () const noexcept
Gets whether the window is resizable.
Returns
True if the window is resizable, and false otherwise.
Referenced by resizable(), and setResizable().
setResizable()
void tr::Window::setResizable (bool resizable) noexcept
Sets whether the window is resizable.
Parameters
[in] resizable Whether the window should be resizable.
Referenced by setResizable().
minSize()
glm::ivec2 tr::Window::minSize () const noexcept
Gets the minimum resizable size of the window.
Returns
The minimum resizable size of the window.
Referenced by minSize(), and setMinSize().
setMinSize()
void tr::Window::setMinSize (glm::ivec2 minSize) noexcept
Sets the minimum resizable size of the window.
Parameters
[in] minSize The minimum resiable size of the window.
Referenced by setMinSize().
maxSize()
glm::ivec2 tr::Window::maxSize () const noexcept
Gets the maximum resizable size of the window.
Returns
The maximum resizable size of the window.
Referenced by maxSize(), and setMaxSize().
setMaxSize()
void tr::Window::setMaxSize (glm::ivec2 maxSize) noexcept
Sets the maximum resizable size of the window.
Parameters
[in] maxSize The maximum resiable size of the window.
Referenced by setMaxSize().
position()
glm::ivec2 tr::Window::position () const noexcept
Gets the position of the window relative to the top-left corner of the display.
Returns
The position of the window relative to the top-left corner of the display in pixels.
Referenced by position().
setPosition()
void tr::Window::setPosition (glm::ivec2 pos) noexcept
Sets the position of the window relative to the top-left corner of the display.
Parameters
[in] pos The new position of the window relative to the top-left corner of the display in pixels.
Referenced by setPosition().
bordered()
bool tr::Window::bordered () const noexcept
Gets whether the window is bordered.
Returns
True if the window is bordered, and false otherwise.
Referenced by bordered(), and setBordered().
setBordered()
void tr::Window::setBordered (bool bordered) noexcept
Sets whether the mouse is bordered.
Parameters
[in] bordered Whether the mouse should be bordered.
Referenced by setBordered().
shown()
bool tr::Window::shown () const noexcept
Gets whether the window is being shown.
Returns
True if the window is being shown, and false otherwise.
Referenced by shown().
show()
void tr::Window::show () noexcept
Unhides the window.
Referenced by show().
hide()
void tr::Window::hide () noexcept
Hides the window.
Referenced by hide().
maximized()
bool tr::Window::maximized () const noexcept
Gets whether the window is maximized.
Returns
True if the window is maximized, and false otherwise.
Referenced by maximized().
maximize()
void tr::Window::maximize () noexcept
Maximizes the window.
Referenced by maximize().
restore()
void tr::Window::restore () noexcept
Restores the window back to its previous size.
Referenced by restore().
minimized()
bool tr::Window::minimized () const noexcept
Gets whether the window is minimized.
Returns
True if the window is minimized, and false otherwise.
Referenced by minimized().
minimize()
void tr::Window::minimize () noexcept
Minimizes the window.
Referenced by minimize().
hasFocus()
bool tr::Window::hasFocus () const noexcept
Gets whether the window has input focus.
Returns
True if the window has input focus, and false otherwise.
Referenced by hasFocus().
raise()
void tr::Window::raise () noexcept
Raises the window above the rest and gives it input focus.
Referenced by raise().
mouseGrabbed()
bool tr::Window::mouseGrabbed () const noexcept
Gets whether the mouse is grabbed and confined to this window.
Returns
True if the mouse is grabbed, and false otherwise.
Referenced by mouseGrabbed().
setMouseGrab()
void tr::Window::setMouseGrab (bool grab) noexcept
Sets whether the mouse is grabbed and confined to this window.
Parameters
[in] grab Whether the mouse should be grabbed.
Referenced by setMouseGrab().
mouseConfines()
std::optional< RectI2 > tr::Window::mouseConfines () const noexcept
Gets the area the mouse is confined to when this window has focus.
Returns
The rectangle to which the mouse is confined to or std::nullopt if it is not set.
Referenced by mouseConfines().
setMouseConfines()
void tr::Window::setMouseConfines (const RectI2 & rect) noexcept
Sets the area the mouse is confined to when this window has focus.
Parameters
[in] rect The confinement rectangle.
Referenced by setMouseConfines().
resetMouseConfines()
void tr::Window::resetMouseConfines () noexcept
Resets the area the mouse is confined to.
Referenced by resetMouseConfines().
alwaysOnTop()
bool tr::Window::alwaysOnTop () const noexcept
Gets whether the window is always on top.
Returns
True if the window is always on top, or false otherwise.
Referenced by alwaysOnTop(), and setAlwaysOnTop().
setAlwaysOnTop()
void tr::Window::setAlwaysOnTop (bool alwaysOnTop) noexcept
Sets whether the window is always on top.
Parameters
[in] alwaysOnTop Whether the window should be always on top.
Referenced by setAlwaysOnTop().
flash()
void tr::Window::flash (FlashOperation operation) noexcept
Flashes the window to get the user's attention.
Parameters
[in] operation The type of flashing to perform.
Referenced by flash().
opacity()
float tr::Window::opacity () const noexcept
Gets the opacity of the window.
Returns
The opacity of the window [0.0, 1.0].
Referenced by opacity(), and setOpacity().
setOpacity()
void tr::Window::setOpacity (float opacity) noexcept
Sets the opacity of the window.
Parameters
opacity The opacity of the window [0.0, 1.0].
Referenced by setOpacity().
vsync()
VSync tr::Window::vsync () const noexcept
Gets the window's V-sync mode.
Returns
The window's V-sync mode.
Referenced by setVSync(), and vsync().
setVSync()
void tr::Window::setVSync (VSync vsync) noexcept
Sets the window's V-sync mode.
Note
If setting the V-sync mode failed and vsync was VSync::ADAPTIVE, regular V-sync will be used.
Parameters
[in] vsync The new V-sync mode.
Referenced by setVSync().
graphics() [1/2]
GraphicsContext & tr::Window::graphics () noexcept
Gets the window's graphics context.
Returns
A mutable reference to the window's graphics context.
Referenced by graphics(), and graphics().
graphics() [2/2]
const GraphicsContext & tr::Window::graphics () const noexcept
Gets the window's graphics context.
Returns
An immutable reference to the window's graphics context.
backbuffer() [1/2]
Backbuffer & tr::Window::backbuffer () noexcept
Gets the window's backbuffer.
Returns
A mutable reference to the window's backbuffer.
Referenced by backbuffer(), and backbuffer().
backbuffer() [2/2]
const Backbuffer & tr::Window::backbuffer () const noexcept
Gets the window's backbuffer.
Returns
An immutable reference to the window's backbuffer.
events() [1/2]
EventQueue & tr::Window::events () noexcept
Gets the window's event queue.
Returns
A mutable reference to the window's event queue.
Referenced by events(), and events().
events() [2/2]
const EventQueue & tr::Window::events () const noexcept
Gets the window's event queue.
Returns
An immutable reference to the window's event queue.
keyboard()
const Keyboard & tr::Window::keyboard () const noexcept
Gets access to the keyboard.
Returns
An immutable reference to the keyboard.
Referenced by keyboard().
mouse() [1/2]
Mouse & tr::Window::mouse () noexcept
Gets access to the mouse.
Returns
A mutable reference to the mouse.
Referenced by mouse(), and mouse().
mouse() [2/2]
const Mouse & tr::Window::mouse () const noexcept
Gets access to the mouse.
Returns
An immutable reference to the mouse.