libtr: tr::Keyboard Class Reference
tr::Keyboard Class Reference
System » Keyboard
Keyboard functionality.
Public Member Functions
bool held (Scancode key) const noexcept
Gets whether a physical keyboard key is held.
Keymods heldMods () const noexcept
Gets a bitmask of the held keyboard modifiers.
bool clipboardHasTest () const noexcept
Gets whether the clipboard contains text.
void setClipboardText (const char *text) noexcept
Sets the clipboard text.
void setClipboardText (const std::string &text) noexcept
Sets the clipboard text.
std::string clipboardText () const
Gets the clipboard text.
Detailed Description
Keyboard functionality.
Note
This class cannot be directly instantiated.
Member Function Documentation
held()
bool tr::Keyboard::held (Scancode key) const noexcept
Gets whether a physical keyboard key is held.
Parameters
key A physical scancode.
Returns
True if the key is held, and false otherwise.
heldMods()
Keymods tr::Keyboard::heldMods () const noexcept
Gets a bitmask of the held keyboard modifiers.
Returns
A bitmask of the held keyboard modifiers.
clipboardHasTest()
bool tr::Keyboard::clipboardHasTest () const noexcept
Gets whether the clipboard contains text.
Returns
True if the clipboard holds text, and false otherwise.
Referenced by clipboardHasTest().
setClipboardText() [1/2]
void tr::Keyboard::setClipboardText (const char * text) noexcept
Sets the clipboard text.
Parameters
[in] text The text to put into the clipboard.
Referenced by setClipboardText(), and setClipboardText().
setClipboardText() [2/2]
void tr::Keyboard::setClipboardText (const std::string & text) noexcept
Sets the clipboard text.
Parameters
[in] text The text to put into the clipboard.
clipboardText()
std::string tr::Keyboard::clipboardText () const
Gets the clipboard text.
Exception Safety
Strong exception guarantee.
Exceptions
std::bad_alloc If allocating the string fails.
Returns
The text that is held in the clipboard.
Referenced by clipboardText().