libtr: tr::Timer Class Reference
tr::Timer Class Reference
Miscellaneous » Timer
Minimal callback timer class.
Public Types
using Callback = std::function<void()>
Public Member Functions
Timer () noexcept=default
Constructs an inactive timer.
template<class Rep, class Period, class CallbackT>
Timer (const std::chrono::duration< Rep, Period > &interval, CallbackT &&callback)
Constructs an active timer.
Timer (Timer &&r) noexcept=default
Move constructs a timer.
~Timer () noexcept
Stops and destroys the timer.
Timer & operator= (Timer &&r) noexcept
Move-assigns a timer.
bool active () const noexcept
Reports whether the timer is active.
Detailed Description
Minimal callback timer class.
An active timer runs a callback function on a separate thread at a regular interval until the timer is destroyed.
Timer is default-constructible, non-copyable, and movable.
Note
The accuracy of the underlying system functions can be as low as 1ms, and although Timer attempts to correct for errors, it's not advised to use it for applications with <1ms resolution.
Member Typedef Documentation
Callback
using tr::Timer::Callback = std::function<void()>
Constructor & Destructor Documentation
Timer() [1/3]
tr::Timer::Timer () default noexcept
Constructs an inactive timer.
Referenced by Timer(), Timer(), ~Timer(), active(), and operator=().
Timer() [2/3]
template<class Rep, class Period, class CallbackT> tr::Timer::Timer (const std::chrono::duration< Rep, Period > & interval, CallbackT && callback)
Constructs an active timer.
Exception Safety
Strong exception guarantee.
Exceptions
std::system_error If launching a thread for the timer failed.
std::bad_alloc If allocating the callback function failed.
Parameters
interval
The interval between ticks.
Precondition
interval must be greater than 0, otherwise the thread will exit immediately.
Parameters
callback The callback function to call on every tick.
Timer() [3/3]
tr::Timer::Timer (Timer && r) default noexcept
Move constructs a timer.
If r was previously in an active state, the thread it was managing will be transferred to the new timer, leaving r in an inactive state.
Parameters
r The timer to move from.
~Timer()
tr::Timer::~Timer () noexcept
Stops and destroys the timer.
Member Function Documentation
operator=()
Timer & tr::Timer::operator= (Timer && r) noexcept
Move-assigns a timer.
If the left-hand timer was previously in an active state, the thread it was managing will be closed as-if by destructor.
If r was previously in an active state, the thread it was managing will be transferred to the new timer, leaving r in an inactive moved-from state.
Parameters
r The timer to move from.
active()
bool tr::Timer::active () const noexcept
Reports whether the timer is active.
Returns
true If the timer is managing a ticking thread, or false otherwise.
Referenced by active().