libtr: tr::Scancode Class Reference
tr::Scancode Class Reference
System » Keyboard
Physical keycode.
Public Types
enum class Enum {
UNKNOWN , A = 4 , B , C ,
D , E , F , G ,
H , I , J , K ,
L , M , N , O ,
P , Q , R , S ,
T , U , V , W ,
X , Y , Z , TOP_ROW_1 ,
TOP_ROW_2 , TOP_ROW_3 , TOP_ROW_4 , TOP_ROW_5 ,
TOP_ROW_6 , TOP_ROW_7 , TOP_ROW_8 , TOP_ROW_9 ,
TOP_ROW_0 , ENTER , ESCAPE , BACKSPACE ,
TAB , SPACE , MINUS , EQUALS ,
LEFT_BRACKET , RIGHT_BRACKET , BACKSLASH , SEMICOLON = 51 ,
APOSTROPHE , GRAVE , COMMA , PERIOD ,
SLASH , CAPSLOCK , F1 , F2 ,
F3 , F4 , F5 , F6 ,
F7 , F8 , F9 , F10 ,
F11 , F12 , PRINT_SCREEN , SCROLL_LOCK ,
PAUSE , INSERT , HOME , PAGE_UP ,
DELETE , END , PAGE_DOWN , RIGHT ,
LEFT , DOWN , UP , NUM_LOCK ,
KEYPAD_DIVIDE , KEYPAD_MULTIPLY , KEYPAD_MINUS , KEYPAD_PLUS ,
KEYPAD_ENTER , KEYPAD_1 , KEYPAD_2 , KEYPAD_3 ,
KEYPAD_4 , KEYPAD_5 , KEYPAD_6 , KEYPAD_7 ,
KEYPAD_8 , KEYPAD_9 , KEYPAD_0 , KEYPAD_PERIOD ,
NONUS_BACKSLASH , APPLICATION , LCTRL = 224 , LSHIFT ,
LALT , LWIN , RCTRL , RSHIFT ,
RALT , RWIN
}
The base enumerator.
Public Member Functions
Scancode () noexcept=default
Scancode (Enum base) noexcept
Constructs a keycode from the base enumerator.
Scancode (const char *name) noexcept
Constructs a scancode by matching it against a key name string.
operator Enum () const noexcept
Casts the scancode back to the base enumerator.
operator Keycode () const noexcept
Converts the scancode to a virtual keycode.
const char * name () const noexcept
Casts the name of the key.
Detailed Description
Physical keycode.
Member Enumeration Documentation
Enum
enum class tr::Scancode::Enum strong
The base enumerator.
Its members are included in the parent class, so it's mostly an implementation detail.
Enumerator
UNKNOWN
A
B
C
D
E
F
G
H
I
J
K
L
M
N
O
P
Q
R
S
T
U
V
W
X
Y
Z
TOP_ROW_1
TOP_ROW_2
TOP_ROW_3
TOP_ROW_4
TOP_ROW_5
TOP_ROW_6
TOP_ROW_7
TOP_ROW_8
TOP_ROW_9
TOP_ROW_0
ENTER
ESCAPE
BACKSPACE
TAB
SPACE
MINUS
EQUALS
LEFT_BRACKET
RIGHT_BRACKET
BACKSLASH
SEMICOLON
APOSTROPHE
GRAVE
COMMA
PERIOD
SLASH
CAPSLOCK
F1
F2
F3
F4
F5
F6
F7
F8
F9
F10
F11
F12
PRINT_SCREEN
SCROLL_LOCK
PAUSE
INSERT
HOME
PAGE_UP
DELETE
END
PAGE_DOWN
RIGHT
LEFT
DOWN
UP
NUM_LOCK
KEYPAD_DIVIDE
KEYPAD_MULTIPLY
KEYPAD_MINUS
KEYPAD_PLUS
KEYPAD_ENTER
KEYPAD_1
KEYPAD_2
KEYPAD_3
KEYPAD_4
KEYPAD_5
KEYPAD_6
KEYPAD_7
KEYPAD_8
KEYPAD_9
KEYPAD_0
KEYPAD_PERIOD
NONUS_BACKSLASH
APPLICATION
LCTRL
LSHIFT
LALT
LWIN
RCTRL
RSHIFT
RALT
RWIN
Constructor & Destructor Documentation
Scancode() [1/3]
tr::Scancode::Scancode () default noexcept
Referenced by Scancode(), and Scancode().
Scancode() [2/3]
tr::Scancode::Scancode (Enum base) noexcept
Constructs a keycode from the base enumerator.
Parameters
[in] base The base enumerator.
Scancode() [3/3]
tr::Scancode::Scancode (const char * name) noexcept
Constructs a scancode by matching it against a key name string.
Parameters
[in] name A key name string. If the name isn't recognised, the keycode will be UNKNOWN.
Member Function Documentation
operator Enum()
tr::Scancode::operator Enum () const noexcept
Casts the scancode back to the base enumerator.
operator Keycode()
tr::Scancode::operator Keycode () const noexcept
Converts the scancode to a virtual keycode.
name()
const char * tr::Scancode::name () const noexcept
Casts the name of the key.
Returns
The name of the key as a C-string.
Referenced by Scancode(), and name().