libtr: tr::BasicFramebuffer Class Reference
tr::BasicFramebuffer Class Reference abstract
System » Graphics » Framebuffers
Base framebuffer class.
Public Member Functions
virtual glm::ivec2 size () const noexcept=0
Gets the size of the framebuffer.
Bitmap readRegion (const RectI2 &rect, BitmapFormat format) const
Reads pixels into a bitmap.
void copyRegion (const RectI2 &rect, Texture2D &texture, glm::ivec2 textureTL) const noexcept
Copies pixels to a texture.
Protected Member Functions
BasicFramebuffer (unsigned int id) noexcept
void bindRead () const noexcept
void bindWrite () const noexcept
Protected Attributes
unsigned int _id
Detailed Description
Base framebuffer class.
Note
This class cannot be instantiated directly.
Constructor & Destructor Documentation
BasicFramebuffer()
tr::BasicFramebuffer::BasicFramebuffer (unsigned int id) protected noexcept
Referenced by BasicFramebuffer().
Member Function Documentation
size()
virtual glm::ivec2 tr::BasicFramebuffer::size () const pure virtual noexcept
Gets the size of the framebuffer.
Returns
The size of the framebuffer in pixels.
Implemented in tr::Backbuffer, and tr::Framebuffer.
readRegion()
Bitmap tr::BasicFramebuffer::readRegion (const RectI2 & rect, BitmapFormat format) const
Reads pixels into a bitmap.
The image is copied from the color attachments bound to the framebuffer.
Exceptions
BitmapBadAlloc If allocating the bitmap fails.
Parameters
[in] rect The rect of the framebuffer to copy.
[in] format The format to use for the bitmap pixels.
Returns
A bitmap containing the pixel data.
Referenced by readRegion().
copyRegion()
void tr::BasicFramebuffer::copyRegion (const RectI2 & rect, Texture2D & texture, glm::ivec2 textureTL) const noexcept
Copies pixels to a texture.
The image is copied from the color attachments bound to the framebuffer.
Parameters
[in] rect The rect of the framebuffer to copy.
[out] texture The texture to copy the pixels to.
[in] textureTL The coordinates of the top-left corner of the rect within the texture.
Referenced by copyRegion().
bindRead()
void tr::BasicFramebuffer::bindRead () const protected noexcept
Referenced by bindRead().
bindWrite()
void tr::BasicFramebuffer::bindWrite () const protected noexcept
Referenced by bindWrite().
Member Data Documentation
_id
unsigned int tr::BasicFramebuffer::_id protected