libtr: tr::DisplayInfo Class Reference
tr::DisplayInfo Class Reference
System » Display
Display information querying object.
Public Member Functions
RectI2 bounds () const noexcept
Queries the bounds of the display.
glm::ivec2 centeredPos () const noexcept
Creates a value usable by a Window constructor for centering a window on the display.
glm::ivec2 toLocalCoords (glm::ivec2 globalCoords) const noexcept
Converts global coordinates to local coordinates on the display.
glm::ivec2 toGlobalCoords (glm::ivec2 localCoords) const noexcept
Converts local coordinates on the display to global coordinates.
int displayModeCount () const noexcept
Gets the number of display modes available on the display.
DisplayMode displayMode (int mode) const noexcept
Gets one of the display's display modes.
std::optional< DisplayMode > closestModeTo (const DisplayMode &mode) const noexcept
Tries to get the closest compatible display mode to the desired one.
Detailed Description
Display information querying object.
Member Function Documentation
bounds()
RectI2 tr::DisplayInfo::bounds () const noexcept
Queries the bounds of the display.
Returns
The bounds of the display.
centeredPos()
glm::ivec2 tr::DisplayInfo::centeredPos () const noexcept
Creates a value usable by a Window constructor for centering a window on the display.
Returns
A sentinel value used by the window's positioning function to center itself on the display.
Referenced by centeredPos().
toLocalCoords()
glm::ivec2 tr::DisplayInfo::toLocalCoords (glm::ivec2 globalCoords) const noexcept
Converts global coordinates to local coordinates on the display.
Parameters
[in] globalCoords The global coordinates to convert.
Returns
The corresponding local coordinates.
Referenced by toLocalCoords().
toGlobalCoords()
glm::ivec2 tr::DisplayInfo::toGlobalCoords (glm::ivec2 localCoords) const noexcept
Converts local coordinates on the display to global coordinates.
Parameters
[in] localCoords The local coordinates on the display to convert.
Returns
The corresponding global coordinates.
Referenced by toGlobalCoords().
displayModeCount()
int tr::DisplayInfo::displayModeCount () const noexcept
Gets the number of display modes available on the display.
Returns
The number of display modes available on the display.
Referenced by displayModeCount().
displayMode()
DisplayMode tr::DisplayInfo::displayMode (int mode) const noexcept
Gets one of the display's display modes.
Parameters
[in] mode
The index of the display mode, HIGHEST_MODE, or DESKTOP_MODE.
Precondition
If an index, mode must be in the range [0, displayModeCount()).
Returns
The requested display modes.
Referenced by displayMode().
closestModeTo()
std::optional< DisplayMode > tr::DisplayInfo::closestModeTo (const DisplayMode & mode) const noexcept
Tries to get the closest compatible display mode to the desired one.
Parameters
[in] mode The mode to look for.
Returns
The closest compatible display mode or std::nullopt if no display is close enough.
Referenced by closestModeTo().