libtr: tr::AudioBuffer Class Reference
tr::AudioBuffer Class Reference
Audio » Audio Buffer
Owning audio data buffer.
Public Member Functions
AudioBuffer ()
Constructs an empty audio buffer.
AudioBuffer (std::span< const std::int16_t > data, AudioFormat format, int frequency)
Constructs an audio buffer and immediately sets it.
AudioBuffer (AudioBuffer &&r) noexcept=default
Move constructs an audio buffer.
~AudioBuffer () noexcept=default
Destroys the audio buffer.
AudioBuffer & operator= (AudioBuffer &&r) noexcept=default
Move assigns an audio buffer.
operator AudioBufferView () const noexcept
Casts the audio buffer to an audio buffer view.
tr::SecondsF length () const noexcept
Gets the length of the buffer.
void set (std::span< const std::int16_t > data, AudioFormat format, int frequency)
Sets the data of the buffer.
Detailed Description
Owning audio data buffer.
AudioBuffer is default-constructible, non-copyable, and movable.
Constructor & Destructor Documentation
AudioBuffer() [1/3]
tr::AudioBuffer::AudioBuffer ()
Constructs an empty audio buffer.
Exception Safety
Strong exception guarantee.
Exceptions
AudioBufferBadAlloc If allocating the buffer fails.
Referenced by AudioBuffer(), and operator=().
AudioBuffer() [2/3]
tr::AudioBuffer::AudioBuffer (std::span< const std::int16_t > data, AudioFormat format, int frequency)
Constructs an audio buffer and immediately sets it.
Exception Safety
Strong exception guarantee.
Exceptions
AudioBufferBadAlloc If allocating the buffer fails.
Parameters
[in] data A span over audio data.
[in] format The format of the audio data.
[in] frequency The frequency of the audio data.
AudioBuffer() [3/3]
tr::AudioBuffer::AudioBuffer (AudioBuffer && r) default noexcept
Move constructs an audio buffer.
Parameters
r The buffer to move from. r will be left in a state where other buffers can be moved into it, but is otherwise unusable.
~AudioBuffer()
tr::AudioBuffer::~AudioBuffer () default noexcept
Destroys the audio buffer.
Precondition
The audio buffer must not be in use.
Member Function Documentation
operator=()
AudioBuffer & tr::AudioBuffer::operator= (AudioBuffer && r) default noexcept
Move assigns an audio buffer.
Precondition
The assigned-to audio buffer must not be in use, as its previous data will be freed.
Parameters
r The buffer to move from. r will be left in a state where other buffers can be moved into it, but is otherwise unusable.
Returns
A reference to the assigned-to buffer.
operator AudioBufferView()
tr::AudioBuffer::operator AudioBufferView () const noexcept
Casts the audio buffer to an audio buffer view.
length()
tr::SecondsF tr::AudioBuffer::length () const noexcept
Gets the length of the buffer.
Returns
The length of the buffer in seconds.
Referenced by length().
set()
void tr::AudioBuffer::set (std::span< const std::int16_t > data, AudioFormat format, int frequency)
Sets the data of the buffer.
Exceptions
AudioBufferBadAlloc If allocating the buffer fails.
Parameters
[in] data A span over audio data.
[in] format The format of the audio data.
[in] frequency The frequency of the audio data.
Referenced by set().