libtr: tr::OwningShaderPipeline Class Reference
tr::OwningShaderPipeline Class Reference
System » Graphics » Shader Pipelines
Shader program pipeline that owns its shaders.
Public Member Functions
OwningShaderPipeline (Shader &&vertexShader, Shader &&fragmentShader) noexcept
Creates an owning shader pipeline.
operator const ShaderPipeline & () const noexcept
Gets the base pipeline object.
Shader & vertexShader () noexcept
Gets the vertex shader.
const Shader & vertexShader () const noexcept
Gets the vertex shader.
Shader & fragmentShader () noexcept
Gets the fragment shader.
const Shader & fragmentShader () const noexcept
Gets the fragment shader.
void setLabel (std::string_view label) noexcept
Sets the debug label of the pipeline.
Detailed Description
Shader program pipeline that owns its shaders.
OwningShaderPipeline is non-copyable and moveable.
Constructor & Destructor Documentation
OwningShaderPipeline()
tr::OwningShaderPipeline::OwningShaderPipeline (Shader && vertexShader, Shader && fragmentShader) noexcept
Creates an owning shader pipeline.
Precondition
All shaders must actually be of the type they're passed as.
Parameters
[in] vertexShader The vertex shader that will be moved into the pipeline.
[in] fragmentShader The fragment shader that will be moved into the pipeline.
Member Function Documentation
operator const ShaderPipeline &()
tr::OwningShaderPipeline::operator const ShaderPipeline & () const noexcept
Gets the base pipeline object.
Returns
A reference to the base pipeline object.
vertexShader() [1/2]
Shader & tr::OwningShaderPipeline::vertexShader () noexcept
Gets the vertex shader.
Returns
A reference to the vertex shader.
Referenced by OwningShaderPipeline(), and vertexShader().
vertexShader() [2/2]
const Shader & tr::OwningShaderPipeline::vertexShader () const noexcept
Gets the vertex shader.
Returns
A constant reference to the vertex shader.
fragmentShader() [1/2]
Shader & tr::OwningShaderPipeline::fragmentShader () noexcept
Gets the fragment shader.
Returns
A reference to the fragment shader.
Referenced by OwningShaderPipeline(), fragmentShader(), and fragmentShader().
fragmentShader() [2/2]
const Shader & tr::OwningShaderPipeline::fragmentShader () const noexcept
Gets the fragment shader.
Returns
A constant reference to the fragment shader.
setLabel()
void tr::OwningShaderPipeline::setLabel (std::string_view label) noexcept
Sets the debug label of the pipeline.
Parameters
[in] label The new label of the pipeline.
Referenced by setLabel().