libtr: tr::Framebuffer Class Reference
tr::Framebuffer Class Reference
System » Graphics » Framebuffers
User framebuffer.
Public Types
enum class Slot {
COLOR0 , COLOR1 , COLOR2 , COLOR3 ,
COLOR4 , COLOR5 , COLOR6 , COLOR7 ,
DEPTH , STENCIL
}
Framebuffer attachment slots.
Public Member Functions
Framebuffer () noexcept
Constructs an empty framebuffer.
Framebuffer (Framebuffer &&move) noexcept
Move-constructs a framebuffer.
~Framebuffer () noexcept
Destroys the framebuffer.
Framebuffer & operator= (Framebuffer &&move) noexcept
Move-assigns a framebuffer.
glm::ivec2 size () const noexcept override
Gets the size of the framebuffer.
void attach (Texture1D &tex, Slot slot) noexcept
Attaches a 1D texture to a slot on the framebuffer.
void attach (ArrayTexture1D &tex, int layer, Slot slot) noexcept
Attaches a layer of a 1D array texture to a slot on the framebuffer.
void attach (Texture2D &tex, Slot slot) noexcept
Attaches a 2D texture to a slot on the framebuffer.
void attach (ArrayTexture2D &tex, int layer, Slot slot) noexcept
Attaches a layer of a 2D array texture to a slot on the framebuffer.
void attach (Texture3D &tex, int z, Slot slot) noexcept
Attaches a layer of a 3D texture to a slot on the framebuffer.
void attach (Renderbuffer &buffer, Slot slot) noexcept
Attaches a renderbuffer to a slot on the framebuffer.
void clear (Slot slot) noexcept
Clears a slot of attachments.
void setLabel (std::string_view label) noexcept
Sets the debug label of the framebuffer.
Public Member Functions inherited from tr::BasicFramebuffer
Bitmap readRegion (const RectI2 &rect, BitmapFormat format) const
Reads pixels into a bitmap.
void copyRegion (const RectI2 &rect, Texture2D &texture, glm::ivec2 textureTL) const noexcept
Copies pixels to a texture.
Additional Inherited Members
Protected Member Functions inherited from tr::BasicFramebuffer
BasicFramebuffer (unsigned int id) noexcept
void bindRead () const noexcept
void bindWrite () const noexcept
Protected Attributes inherited from tr::BasicFramebuffer
unsigned int _id
Detailed Description
User framebuffer.
Member Enumeration Documentation
Slot
enum class tr::Framebuffer::Slot strong
Framebuffer attachment slots.
Enumerator
COLOR0
Color attachment slot 0.
COLOR1
Color attachment slot 1.
COLOR2
Color attachment slot 2.
COLOR3
Color attachment slot 3.
COLOR4
Color attachment slot 4.
COLOR5
Color attachment slot 5.
COLOR6
Color attachment slot 6.
COLOR7
Color attachment slot 7.
DEPTH
Depth attachment slot.
STENCIL
Stencil attachment slot.
Constructor & Destructor Documentation
Framebuffer() [1/2]
tr::Framebuffer::Framebuffer () noexcept
Constructs an empty framebuffer.
Referenced by Framebuffer(), ~Framebuffer(), and operator=().
Framebuffer() [2/2]
tr::Framebuffer::Framebuffer (Framebuffer && move) noexcept
Move-constructs a framebuffer.
Parameters
move The framebuffer to be moved.
~Framebuffer()
tr::Framebuffer::~Framebuffer () noexcept
Destroys the framebuffer.
Member Function Documentation
operator=()
Framebuffer & tr::Framebuffer::operator= (Framebuffer && move) noexcept
Move-assigns a framebuffer.
Parameters
move The framebuffer to be moved.
Returns
A reference to the assigned framebuffer.
size()
glm::ivec2 tr::Framebuffer::size () const override virtual noexcept
Gets the size of the framebuffer.
Returns
The size of the framebuffer in pixels.
Implements tr::BasicFramebuffer.
Referenced by size().
attach() [1/6]
void tr::Framebuffer::attach (Texture1D & tex, Slot slot) noexcept
Attaches a 1D texture to a slot on the framebuffer.
Note
The viewport of the framebuffer will be clamped to the minimum size of all attachments.
Parameters
tex The texture to attach.
slot The slot to attach the texture to.
Referenced by attach(), attach(), attach(), attach(), attach(), and attach().
attach() [2/6]
void tr::Framebuffer::attach (ArrayTexture1D & tex, int layer, Slot slot) noexcept
Attaches a layer of a 1D array texture to a slot on the framebuffer.
Note
The viewport of the framebuffer will be clamped to the minimum size of all attachments.
Parameters
tex The texture to attach.
[in] layer The layer of the texture to attach.
slot The slot to attach the texture to.
attach() [3/6]
void tr::Framebuffer::attach (Texture2D & tex, Slot slot) noexcept
Attaches a 2D texture to a slot on the framebuffer.
Note
The viewport of the framebuffer will be clamped to the minimum size of all attachments.
Parameters
tex The texture to attach.
slot The slot to attach the texture to.
attach() [4/6]
void tr::Framebuffer::attach (ArrayTexture2D & tex, int layer, Slot slot) noexcept
Attaches a layer of a 2D array texture to a slot on the framebuffer.
Note
The viewport of the framebuffer will be clamped to the minimum size of all attachments.
Parameters
tex The texture to attach.
[in] layer The layer of the texture to attach.
slot The slot to attach the texture to.
attach() [5/6]
void tr::Framebuffer::attach (Texture3D & tex, int z, Slot slot) noexcept
Attaches a layer of a 3D texture to a slot on the framebuffer.
Note
The viewport of the framebuffer will be clamped to the minimum size of all attachments.
Parameters
tex The texture to attach.
z The z layer of the texture to attach.
slot The slot to attach the texture to.
attach() [6/6]
void tr::Framebuffer::attach (Renderbuffer & buffer, Slot slot) noexcept
Attaches a renderbuffer to a slot on the framebuffer.
Note
The viewport of the framebuffer will be clamped to the minimum size of all attachments.
Parameters
buffer The renderbuffer to attach.
slot The slot to attach the texture to.
clear()
void tr::Framebuffer::clear (Slot slot) noexcept
Clears a slot of attachments.
Note
The viewport of the framebuffer will be clamped to the minimum size of all attachments.
Parameters
slot The slot to clear.
Referenced by clear().
setLabel()
void tr::Framebuffer::setLabel (std::string_view label) noexcept
Sets the debug label of the framebuffer.
Parameters
[in] label The new label of the framebuffer.
Referenced by setLabel().