libtr: tr::Texture Class Reference
tr::Texture Class Reference
System » Graphics » Textures
Base texture class.
Public Member Functions
TextureFormat format () const noexcept
Gets the format of the texture.
void setSwizzle (Swizzle r, Swizzle g, Swizzle b, Swizzle a) noexcept
Sets the swizzle parameters of the texture.
void setMinFilter (MinFilter filter) noexcept
Sets the minifying filter used by the texture sampler.
void setMagFilter (MagFilter filter) noexcept
Sets the magnifying filter used by the texture sampler.
void disableComparison () noexcept
Disables the use of depth comparison.
void setComparisonMode (Compare op) noexcept
Enables the use of depth comparison and sets the depth comparison operator of the texture sampler.
void setWrap (Wrap wrap) noexcept
Sets the wrapping used for by the texture sampler.
void setBorderColor (RGBAF color) noexcept
Sets the border color of the texture sampler (used when Wrap::BORDER_CLAMP is in use).
void setLabel (std::string_view label) noexcept
Sets the debug label of the texture.
Detailed Description
Base texture class.
Note
This class cannot be constructed directly.
Member Function Documentation
format()
TextureFormat tr::Texture::format () const noexcept
Gets the format of the texture.
Returns
The texture format.
Referenced by tr::ArrayTexture1D::ArrayTexture1D(), tr::ArrayTexture1D::ArrayTexture1D(), tr::ArrayTexture2D::ArrayTexture2D(), tr::ArrayTexture2D::ArrayTexture2D(), tr::Texture1D::Texture1D(), tr::Texture1D::Texture1D(), tr::Texture2D::Texture2D(), tr::Texture2D::Texture2D(), tr::Texture3D::Texture3D(), and tr::Texture3D::Texture3D().
setSwizzle()
void tr::Texture::setSwizzle (Swizzle r, Swizzle g, Swizzle b, Swizzle a) noexcept
Sets the swizzle parameters of the texture.
Parameters
[in] r,g,b,a The new swizzles.
Referenced by setSwizzle().
setMinFilter()
void tr::Texture::setMinFilter (MinFilter filter) noexcept
Sets the minifying filter used by the texture sampler.
Parameters
[in] filter The new minifying filter type.
Referenced by setMinFilter().
setMagFilter()
void tr::Texture::setMagFilter (MagFilter filter) noexcept
Sets the magnifying filter used by the texture sampler.
Parameters
[in] filter The new magnifying filter type.
Referenced by setMagFilter().
disableComparison()
void tr::Texture::disableComparison () noexcept
Disables the use of depth comparison.
Referenced by disableComparison().
setComparisonMode()
void tr::Texture::setComparisonMode (Compare op) noexcept
Enables the use of depth comparison and sets the depth comparison operator of the texture sampler.
Parameters
[in] op The function to use for comparison.
Referenced by setComparisonMode().
setWrap()
void tr::Texture::setWrap (Wrap wrap) noexcept
Sets the wrapping used for by the texture sampler.
Parameters
[in] wrap The new wrapping type.
Referenced by setWrap().
setBorderColor()
void tr::Texture::setBorderColor (RGBAF color) noexcept
Sets the border color of the texture sampler (used when Wrap::BORDER_CLAMP is in use).
Parameters
[in] color The border color in floating point RGBA format.
Referenced by setBorderColor().
setLabel()
void tr::Texture::setLabel (std::string_view label) noexcept
Sets the debug label of the texture.
Parameters
[in] label The new label of the texture.
Referenced by setLabel().