libtr: tr::Listener Class Reference
tr::Listener Class Reference
Audio » Listener
Global audio listener.
Public Member Functions
float gain () const noexcept
Gets the master gain.
void setGain (float gain) noexcept
Sets the master gain.
glm::vec3 position () const noexcept
Gets the position of the listener.
void setPosition (const glm::vec3 &position) noexcept
Sets the position of the listener.
glm::vec3 velocity () const noexcept
Gets the velocity of the listener.
void setVelocity (const glm::vec3 &velocity) noexcept
Sets the velocity of the listener.
Orientation orientation () const noexcept
Gets the orientation of the listener.
void setOrientation (Orientation orientation) noexcept
Sets the orientation of the listener.
Detailed Description
Global audio listener.
Member Function Documentation
gain()
float tr::Listener::gain () const noexcept
Gets the master gain.
Returns
The master gain factor.
Referenced by setGain().
setGain()
void tr::Listener::setGain (float gain) noexcept
Sets the master gain.
Parameters
gain The new gain factor (mul/div 2 = +/- 6.0dB).
Referenced by setGain().
position()
glm::vec3 tr::Listener::position () const noexcept
Gets the position of the listener.
Returns
The position of the listener.
Referenced by position(), and setPosition().
setPosition()
void tr::Listener::setPosition (const glm::vec3 & position) noexcept
Sets the position of the listener.
Parameters
position The new position of the listener.
Referenced by setPosition().
velocity()
glm::vec3 tr::Listener::velocity () const noexcept
Gets the velocity of the listener.
Returns
The velocity of the listener.
Referenced by setVelocity(), and velocity().
setVelocity()
void tr::Listener::setVelocity (const glm::vec3 & velocity) noexcept
Sets the velocity of the listener.
Parameters
velocity The new velocity of the listener.
Referenced by setVelocity().
orientation()
Orientation tr::Listener::orientation () const noexcept
Gets the orientation of the listener.
Returns
The orientation of the listener.
Referenced by orientation(), and setOrientation().
setOrientation()
void tr::Listener::setOrientation (Orientation orientation) noexcept
Sets the orientation of the listener.
Parameters
orientation The new orientation of the listener.
Referenced by setOrientation().