libtr: tr::ColorTexture2D Class Reference
tr::ColorTexture2D Class Reference
System » Graphics » Textures
Two-dimensional color texture.
Public Member Functions
ColorTexture2D (glm::ivec2 size, bool mipmapped=false, ColorTextureFormat format=ColorTextureFormat::RGBA8)
Allocates an uninitialized 2D color texture.
ColorTexture2D (SubBitmap bitmap, bool mipmapped=false, ColorTextureFormat format=ColorTextureFormat::RGBA8)
Constructs a 2D color texture with data uploaded from a bitmap.
glm::ivec2 size () const noexcept
Gets the size of the texture.
void clearRegion (const RectI2 &rect, const tr::RGBAF &color) noexcept
Clears a region of the texture.
void copyRegion (glm::ivec2 tl, const ColorTexture2D &src, const RectI2 &rect) noexcept
Copies a region from another texture.
void setRegion (glm::ivec2 tl, SubBitmap bitmap) noexcept
Sets a region of the texture.
Public Member Functions inherited from tr::ColorTexture
void setSwizzle (Swizzle r, Swizzle g, Swizzle b, Swizzle a) noexcept
Sets the swizzle parameters of the texture.
void setBorderColor (RGBAF color) noexcept
Sets the border color of the texture sampler (used when Wrap::BORDER_CLAMP is in use).
void clear (const RGBAF &color) noexcept
Clears the texture.
Public Member Functions inherited from tr::Texture
void setMinFilter (MinFilter filter) noexcept
Sets the minifying filter used by the texture sampler.
void setMagFilter (MagFilter filter) noexcept
Sets the magnifying filter used by the texture sampler.
void setWrap (Wrap wrap) noexcept
Sets the wrapping used for by the texture sampler.
void setLabel (std::string_view label) noexcept
Sets the debug label of the texture.
Additional Inherited Members
Protected Member Functions inherited from tr::ColorTexture
void clearRegion (const RectI3 &region, const RGBAF &color) noexcept
Detailed Description
Two-dimensional color texture.
Constructor & Destructor Documentation
ColorTexture2D() [1/2]
tr::ColorTexture2D::ColorTexture2D (glm::ivec2 size, bool mipmapped = false, ColorTextureFormat format = ColorTextureFormat::RGBA8)
Allocates an uninitialized 2D color texture.
Exception Safety
Strong exception guarantee.
Exceptions
TextureBadAlloc If allocating the texture fails.
Parameters
[in] size The size of the texture in texels.
[in] mipmapped Whether the texture will be mipmapped.
[in] format The internal format of the texture.
Referenced by copyRegion().
ColorTexture2D() [2/2]
tr::ColorTexture2D::ColorTexture2D (SubBitmap bitmap, bool mipmapped = false, ColorTextureFormat format = ColorTextureFormat::RGBA8)
Constructs a 2D color texture with data uploaded from a bitmap.
Exception Safety
Strong exception guarantee.
Exceptions
TextureBadAlloc If allocating the texture fails.
Parameters
[in] bitmap The bitmap data.
[in] mipmapped Whether the texture will be mipmapped.
[in] format The internal format of the texture.
Member Function Documentation
size()
glm::ivec2 tr::ColorTexture2D::size () const noexcept
Gets the size of the texture.
Returns
The size of the texture in texels.
Referenced by ColorTexture2D().
clearRegion()
void tr::ColorTexture2D::clearRegion (const RectI2 & rect, const tr::RGBAF & color) noexcept
Clears a region of the texture.
Precondition
The region must fully be inside the bounds of the texture.
Parameters
[in] rect The region to clear.
[in] color The color to clear the region to.
Referenced by clearRegion().
copyRegion()
void tr::ColorTexture2D::copyRegion (glm::ivec2 tl, const ColorTexture2D & src, const RectI2 & rect) noexcept
Copies a region from another texture.
Precondition
The region must fully be inside the bounds of the texture.
Parameters
[in] tl The top-left corner of the region within the texture.
[in] src The texture to copy from.
[in] rect The bounds of the copied region within the source texture.
Referenced by copyRegion().
setRegion()
void tr::ColorTexture2D::setRegion (glm::ivec2 tl, SubBitmap bitmap) noexcept
Sets a region of the texture.
Precondition
The region must fully be inside the bounds of the texture.
Parameters
[in] tl The top-left corner of the region within the texture.
[in] bitmap The bitmap data to set the region to.
Referenced by setRegion().