libtr: tr::ColorTexture3D Class Reference
tr::ColorTexture3D Class Reference
System » Graphics » Textures
Three-dimensional color texture.
Public Member Functions
ColorTexture3D (glm::ivec3 size, bool mipmapped=false, ColorTextureFormat format=ColorTextureFormat::RGBA8)
Allocates an uninitialized 3D color texture.
ColorTexture3D (std::span< SubBitmap > layers, bool mipmapped=false, ColorTextureFormat format=ColorTextureFormat::RGBA8)
Constructs a 3D color texture with data uploaded from a list of bitmaps.
glm::ivec3 size () const noexcept
Gets the size of the texture.
void clearRegion (const RectI3 &rect, const tr::RGBAF &color) noexcept
Clears a region of the texture.
void copyRegion (const glm::ivec3 &offset, const ColorTexture3D &src, const RectI3 &rect) noexcept
Copies a region from another texture.
void setLayerRegion (const glm::ivec3 &tl, SubBitmap bitmap) noexcept
Sets a region of a Z layer.
Public Member Functions inherited from tr::ColorTexture
void setSwizzle (Swizzle r, Swizzle g, Swizzle b, Swizzle a) noexcept
Sets the swizzle parameters of the texture.
void setBorderColor (RGBAF color) noexcept
Sets the border color of the texture sampler (used when Wrap::BORDER_CLAMP is in use).
void clear (const RGBAF &color) noexcept
Clears the texture.
Public Member Functions inherited from tr::Texture
void setMinFilter (MinFilter filter) noexcept
Sets the minifying filter used by the texture sampler.
void setMagFilter (MagFilter filter) noexcept
Sets the magnifying filter used by the texture sampler.
void setWrap (Wrap wrap) noexcept
Sets the wrapping used for by the texture sampler.
void setLabel (std::string_view label) noexcept
Sets the debug label of the texture.
Additional Inherited Members
Protected Member Functions inherited from tr::ColorTexture
void clearRegion (const RectI3 &region, const RGBAF &color) noexcept
Detailed Description
Three-dimensional color texture.
Constructor & Destructor Documentation
ColorTexture3D() [1/2]
tr::ColorTexture3D::ColorTexture3D (glm::ivec3 size, bool mipmapped = false, ColorTextureFormat format = ColorTextureFormat::RGBA8)
Allocates an uninitialized 3D color texture.
Exception Safety
Strong exception guarantee.
Exceptions
TextureBadAlloc If allocating the texture fails.
Parameters
[in] size The size of the texture in texels.
[in] mipmapped Whether the texture will be mipmapped.
[in] format The internal format of the texture.
Referenced by copyRegion().
ColorTexture3D() [2/2]
tr::ColorTexture3D::ColorTexture3D (std::span< SubBitmap > layers, bool mipmapped = false, ColorTextureFormat format = ColorTextureFormat::RGBA8)
Constructs a 3D color texture with data uploaded from a list of bitmaps.
Exception Safety
Strong exception guarantee.
Exceptions
TextureBadAlloc If allocating the texture fails.
Parameters
[in] layers
The Z layer bitmaps.
Precondition
layers cannot be empty, and the bitmaps must all be of the same size.
Parameters
[in] mipmapped Whether the texture will be mipmapped.
[in] format The internal format of the texture.
Member Function Documentation
size()
glm::ivec3 tr::ColorTexture3D::size () const noexcept
Gets the size of the texture.
Returns
The size of the texture in texels.
Referenced by ColorTexture3D().
clearRegion()
void tr::ColorTexture3D::clearRegion (const RectI3 & rect, const tr::RGBAF & color) noexcept
Clears a region of the texture.
Precondition
The region must fully be inside the bounds of the texture.
Parameters
[in] rect The region to clear.
[in] color The color to clear the region to.
Referenced by clearRegion().
copyRegion()
void tr::ColorTexture3D::copyRegion (const glm::ivec3 & offset, const ColorTexture3D & src, const RectI3 & rect) noexcept
Copies a region from another texture.
Precondition
The region must fully be inside the bounds of the texture.
Parameters
[in] offset The offset within the texture.
[in] src The texture to copy from.
[in] rect The bounds of the copied region within the source texture.
Referenced by copyRegion().
setLayerRegion()
void tr::ColorTexture3D::setLayerRegion (const glm::ivec3 & tl, SubBitmap bitmap) noexcept
Sets a region of a Z layer.
Precondition
The region must fully be inside the bounds of the texture.
Parameters
[in] tl The top-left corner of the region within the texture.
[in] bitmap The bitmap data to set the region to.
Referenced by setLayerRegion().