libtr: draw_geometry.hpp File Reference
draw_geometry.hpp File Reference
Provides common geometry output functions used in drawing.
#include "geometry.hpp"
Functions
template<std::output_iterator< glm::vec2 > It>
void tr::fillArcVertices (It out, std::size_t vertices, CircleF circ, AngleF startth, AngleF sizeth)
Outputs vertex positions along an arc.
template<std::output_iterator< std::uint16_t > It>
constexpr void tr::fillPolygonIndices (It out, std::uint16_t vertices, std::uint16_t base)
Outputs indices for a convex polygon.
template<std::output_iterator< std::uint16_t > It>
constexpr void tr::fillPolygonOutlineIndices (It out, std::uint16_t vertices, std::uint16_t base)
Outputs indices for a convex polygon outline.
template<std::output_iterator< glm::vec2 > It>
void tr::fillPolygonOutlineVertices (It out, std::size_t vertices, CircleF circ, AngleF rotation, float thickness)
Outputs vertex positions for a regular polygon's outline.
template<std::output_iterator< glm::vec2 > It>
void tr::fillPolygonVertices (It out, std::size_t vertices, CircleF circ, AngleF rotation=0_degf)
Outputs vertex positions for a regular polygon.
template<std::output_iterator< glm::vec2 > It>
constexpr void tr::fillRectVertices (It out, glm::vec2 tl, glm::vec2 size)
Outputs unrotated rectangle vertices.
std::size_t tr::smoothArcVerticesCount (float r, AngleF sizeth) noexcept
Calculates the number of segments needed to draw a smooth arc.
std::size_t tr::smoothPolygonVerticesCount (float r) noexcept
Calculates the number of segments needed to draw a smooth circle with pixel radius r.
Detailed Description
Provides common geometry output functions used in drawing.
Function Documentation
fillArcVertices()
template<std::output_iterator< glm::vec2 > It> void tr::fillArcVertices (It out, std::size_t vertices, CircleF circ, AngleF startth, AngleF sizeth)
Outputs vertex positions along an arc.
Template Parameters
It A position vector output iterator type.
Parameters
out The output iterator. There has to be space for all of the vertices.
vertices The number of vertices on the arc.
circ The arc circle.
startth The starting angle on the arc circle of the arc.
sizeth The angular size of the arc.
Referenced by tr::fillArcVertices().
fillPolygonIndices()
template<std::output_iterator< std::uint16_t > It> void tr::fillPolygonIndices (It out, std::uint16_t vertices, std::uint16_t base) constexpr
Outputs indices for a convex polygon.
Template Parameters
It An index output iterator type.
Parameters
out The output iterator. There has to be space for (vertices - 2) * 3 indices.
vertices The number of vertices in the polygon. Must be greater than 2.
base The "base" index offset added to every index value.
Referenced by tr::fillPolygonIndices().
fillPolygonOutlineIndices()
template<std::output_iterator< std::uint16_t > It> void tr::fillPolygonOutlineIndices (It out, std::uint16_t vertices, std::uint16_t base) constexpr
Outputs indices for a convex polygon outline.
Template Parameters
It An index output iterator type.
Parameters
out The output iterator. There has to be space for (vertices - 2) * 6 indices.
vertices The number of vertices in the polygon. Must be greater than 2.
base The "base" index offset added to every index value.
Referenced by tr::fillPolygonOutlineIndices().
fillPolygonOutlineVertices()
template<std::output_iterator< glm::vec2 > It> void tr::fillPolygonOutlineVertices (It out, std::size_t vertices, CircleF circ, AngleF rotation, float thickness)
Outputs vertex positions for a regular polygon's outline.
Template Parameters
It A position vector output iterator type.
Parameters
out The output iterator. There has to be space for vertices * 2.
vertices The number of polygon vertices.
circ The tangent circle of the polygon.
rotation The rotation of the polygon.
thickness The thickness of the polygon.
Referenced by tr::fillPolygonOutlineVertices().
fillPolygonVertices()
template<std::output_iterator< glm::vec2 > It> void tr::fillPolygonVertices (It out, std::size_t vertices, CircleF circ, AngleF rotation = 0_degf)
Outputs vertex positions for a regular polygon.
Template Parameters
It A position vector output iterator type.
Parameters
out The output iterator. There has to be space for all of the vertices.
vertices The number of polygon vertices.
circ The tangent circle of the polygon.
rotation The rotation of the polygon.
Referenced by tr::fillPolygonVertices().
fillRectVertices()
template<std::output_iterator< glm::vec2 > It> void tr::fillRectVertices (It out, glm::vec2 tl, glm::vec2 size) constexpr
Outputs unrotated rectangle vertices.
Template Parameters
It A position vector output iterator type.
Parameters
out The output iterator. There has to be space for 4 vertices.
tl The position of the top-left corner of the rectangle.
size The size of the rectangle
Referenced by tr::fillRectVertices().
smoothArcVerticesCount()
std::size_t tr::smoothArcVerticesCount (float r, AngleF sizeth) inline noexcept
Calculates the number of segments needed to draw a smooth arc.
Parameters
r The radius of the arc circle. Must be in the range (0, +Inf.).
sizeth The angular size of the arc. Must be in the range (0, 360deg).
Returns
The number of segments needed to draw a smooth arc.
Referenced by tr::smoothArcVerticesCount().
smoothPolygonVerticesCount()
std::size_t tr::smoothPolygonVerticesCount (float r) inline noexcept
Calculates the number of segments needed to draw a smooth circle with pixel radius r.
Parameters
r The radius of the circle. Must be in the range (0, +Inf.).
Returns
The number of segments needed to draw a smooth circle with pixel radius r.
Referenced by tr::smoothPolygonVerticesCount().