libtr: geometry.hpp File Reference
geometry.hpp File Reference
Provides various geometry functions.
#include "angle.hpp"
#include <glm/ext.hpp>
#include <glm/glm.hpp>
#include <optional>
Classes
struct tr::Circle< T >
2D circle.
struct tr::Rect< S, T >
Rectangle object.
Namespaces
namespace tr::matrix_operators
Matrix multiplication operators.
Typedefs
using tr::CircleF = Circle<float>
Shorthand for a float circle.
template<class T >
using tr::Rect2 = Rect<2, T>
2D rectangle.
template<class T >
using tr::Rect3 = Rect<3, T>
3D rectangle.
using tr::RectF2 = Rect2<float>
Shorthand for a float 2D rect.
using tr::RectF3 = Rect3<float>
Shorthand for a float 3D rect.
using tr::RectI2 = Rect2<int>
Shorthand for an int 2D rect.
using tr::RectI3 = Rect3<int>
Shorthand for an int 3D rect.
Functions
template<std::floating_point T>
constexpr glm::tvec2< T > tr::closestPoint (glm::tvec2< T > p, glm::tvec2< T > a, glm::tvec2< T > b) noexcept
Calculates the closest point to p on the line ab.
template<std::integral T>
constexpr glm::dvec2 tr::closestPoint (glm::tvec2< T > p, glm::tvec2< T > a, glm::tvec2< T > b) noexcept
Calculates the closest point to p on the line ab.
template<class T1 , class T2 , class T3 >
constexpr bool tr::collinear (glm::tvec2< T1 > a, glm::tvec2< T2 > b, glm::tvec2< T3 > c) noexcept
Determines whether 3 points are collinear.
template<class T1 , class T2 >
constexpr std::common_type_t< T1, T2 > tr::cross2 (glm::tvec2< T1 > a, glm::tvec2< T2 > b) noexcept
Calculates the 2D cross product of two vectors.
template<std::floating_point T>
std::optional< glm::tvec2< T > > tr::intersect (glm::tvec2< T > a1, Angle< T > th1, glm::tvec2< T > a2, Angle< T > th2) noexcept
Calculates the intersection point of two lines.
template<std::floating_point T>
std::optional< glm::tvec2< T > > tr::intersect (glm::tvec2< T > a1, Angle< T > th1, glm::tvec2< T > a2, glm::tvec2< T > b2) noexcept
Calculates the intersection point of two lines.
template<std::integral T>
std::optional< glm::dvec2 > tr::intersect (glm::tvec2< T > a1, AngleD th1, glm::tvec2< T > a2, AngleD th2) noexcept
Calculates the intersection point of two lines.
template<std::floating_point T>
constexpr std::optional< glm::tvec2< T > > tr::intersect (glm::tvec2< T > a1, glm::tvec2< T > b1, glm::tvec2< T > a2, glm::tvec2< T > b2) noexcept
Calculates the intersection point of two lines.
template<class T >
bool tr::intersecting (const Circle< T > &c1, const Circle< T > &c2) noexcept
Determines if two circles intersect.
template<class T1 , class T2 >
bool tr::intersecting (const Rect2< T1 > &r1, const Rect2< T2 > &r2) noexcept
Determines if two rects intersect.
template<std::size_t S, std::floating_point T>
constexpr glm::vec< S, T > tr::inverse (const glm::vec< S, T > &vec) noexcept
Gets the inverse of a vector.
template<std::size_t S, std::integral T>
constexpr glm::vec< S, double > tr::inverse (const glm::vec< S, T > &vec) noexcept
Gets the inverse of a vector.
template<int S, class T >
glm::vec< S, T > tr::mirrorRepeat (const glm::vec< S, T > &v, const glm::vec< S, T > &min, const glm::vec< S, T > &max) noexcept
Performs a mirror repeat mapping.
template<std::size_t S, class T >
glm::vec< S, T > tr::mirrorRepeat (const glm::vec< S, T > &v, const Rect< S, T > &rect) noexcept
Performs a mirror repeat mapping of a vector on a rect.
template<Arithmetic T>
T tr::mirrorRepeat (T v, T min, T max) noexcept
Performs a mirror repeat mapping.
template<Arithmetic T1, Arithmetic T2>
std::common_type_t< T1, T2 > tr::mod (T1 v, T2 mod) noexcept
Generic modulo operation.
template<class T >
constexpr glm::tvec2< T > tr::matrix_operators::operator* (const glm::tmat4x4< T > &m, const glm::tvec2< T > &v) noexcept
Performs matrix multiplication on a 2D vector.
template<class T >
constexpr glm::tvec3< T > tr::matrix_operators::operator* (const glm::tmat4x4< T > &m, const glm::tvec3< T > &v) noexcept
Performs matrix multiplication on a 3D vector.
template<class T >
constexpr glm::tvec2< T > tr::matrix_operators::operator* (const glm::tvec2< T > &v, const glm::tmat4x4< T > &m) noexcept
Performs matrix multiplication on a 2D vector.
template<class T >
constexpr glm::tvec3< T > tr::matrix_operators::operator* (const glm::tvec3< T > &v, const glm::tmat4x4< T > &m) noexcept
Performs matrix multiplication on a 3D vector.
template<class T >
glm::tmat4x4< T > tr::rotateAroundPoint2 (const glm::tmat4x4< T > &matrix, const glm::tvec2< T > &center, const Angle< T > &angle) noexcept
Applies a 2D rotation around a point to a matrix.
template<class T >
glm::tmat4x4< T > tr::rotateAroundPoint3 (const glm::tmat4x4< T > &matrix, const glm::tvec3< T > &center, const Angle< T > &angle, const glm::tvec3< T > &axis) noexcept
Applies a 3D rotation around a point to a matrix.
template<class T >
glm::tmat4x4< T > tr::scaleAroundPoint2 (const glm::tmat4x4< T > &matrix, const glm::tvec2< T > &center, const glm::tvec2< T > &scale) noexcept
Applies a 2D scaling around a point to a matrix.
template<class T >
glm::tmat4x4< T > tr::scaleAroundPoint3 (const glm::tmat4x4< T > &matrix, const glm::tvec3< T > &center, const glm::tvec3< T > &scale) noexcept
Applies a 3D scaling around a point to a matrix.
template<std::floating_point T>
std::optional< glm::tvec2< T > > tr::segmentIntersect (glm::tvec2< T > a1, Angle< T > th1, glm::tvec2< T > a2, glm::tvec2< T > b2) noexcept
Calculates the intersection point of a line with a line segment.
template<std::integral T>
std::optional< glm::dvec2 > tr::segmentIntersect (glm::tvec2< T > a1, AngleD th1, glm::tvec2< T > a2, glm::tvec2< T > b2) noexcept
Calculates the intersection point of a line with a line segment.
template<std::floating_point T>
constexpr std::optional< glm::tvec2< T > > tr::segmentIntersect (glm::tvec2< T > a1, glm::tvec2< T > b1, glm::tvec2< T > a2, glm::tvec2< T > b2) noexcept
Calculates the intersection point of two line segments.
template<std::integral T>
constexpr std::optional< glm::dvec2 > tr::segmentIntersect (glm::tvec2< T > a1, glm::tvec2< T > b1, glm::tvec2< T > a2, glm::tvec2< T > b2) noexcept
Calculates the intersection point of two line segments.
Variables
constexpr glm::vec3 tr::X_AXIS {1.0f, 0.0f, 0.0f}
Normalized X-axis vector.
constexpr glm::vec3 tr::Y_AXIS {0.0f, 1.0f, 0.0f}
Normalized Y-axis vector.
constexpr glm::vec3 tr::Z_AXIS {0.0f, 0.0f, 1.0f}
Normalized Z-axis vector.
Detailed Description
Provides various geometry functions.
Function Documentation
closestPoint() [1/2]
template<std::floating_point T> glm::tvec2< T > tr::closestPoint (glm::tvec2< T > p, glm::tvec2< T > a, glm::tvec2< T > b) constexpr noexcept
Calculates the closest point to p on the line ab.
Parameters
p A point.
a,b The start and end point of the line segment.
Returns
The closest point to p located on the line ab.
Referenced by tr::closestPoint().
closestPoint() [2/2]
template<std::integral T> glm::dvec2 tr::closestPoint (glm::tvec2< T > p, glm::tvec2< T > a, glm::tvec2< T > b) constexpr noexcept
Calculates the closest point to p on the line ab.
Parameters
p A point.
a,b The start and end point of the line segment.
Returns
The closest point to p located on the line ab.
collinear()
template<class T1 , class T2 , class T3 > bool tr::collinear (glm::tvec2< T1 > a, glm::tvec2< T2 > b, glm::tvec2< T3 > c) constexpr noexcept
Determines whether 3 points are collinear.
Parameters
a,b,c The points to check for collinearity.
Returns
True if the points are collinear, and false otherwise.
Referenced by tr::collinear().
cross2()
template<class T1 , class T2 > std::common_type_t< T1, T2 > tr::cross2 (glm::tvec2< T1 > a, glm::tvec2< T2 > b) constexpr noexcept
Calculates the 2D cross product of two vectors.
Parameters
a,b The two vectors.
Returns
The 2D cross product of the vectors, standard promotion rules apply.
Referenced by tr::cross2().
intersect() [1/4]
template<std::floating_point T> std::optional< glm::tvec2< T > > tr::intersect (glm::tvec2< T > a1, Angle< T > th1, glm::tvec2< T > a2, Angle< T > th2) noexcept
Calculates the intersection point of two lines.
Parameters
a1,th1 Point and angle of the first line.
a2,th2 Point and angle of the second line.
Returns
The intersection point, if one exists.
Referenced by tr::intersect(), tr::intersect(), tr::intersect(), and tr::intersect().
intersect() [2/4]
template<std::floating_point T> std::optional< glm::tvec2< T > > tr::intersect (glm::tvec2< T > a1, Angle< T > th1, glm::tvec2< T > a2, glm::tvec2< T > b2) noexcept
Calculates the intersection point of two lines.
Parameters
a1,th1 Point and angle of the first line.
a2,b2 Two points on the second line.
Returns
The intersection point, if one exists.
intersect() [3/4]
template<std::integral T> std::optional< glm::dvec2 > tr::intersect (glm::tvec2< T > a1, AngleD th1, glm::tvec2< T > a2, AngleD th2) noexcept
Calculates the intersection point of two lines.
Parameters
a1,th1 Point and angle of the first line.
a2,th2 Point and angle of the second line.
Returns
The intersection point, if one exists.
intersect() [4/4]
template<std::floating_point T> std::optional< glm::tvec2< T > > tr::intersect (glm::tvec2< T > a1, glm::tvec2< T > b1, glm::tvec2< T > a2, glm::tvec2< T > b2) constexpr noexcept
Calculates the intersection point of two lines.
Parameters
a1,b1 Two points on the first line.
a2,b2 Two points on the second line.
Returns
The intersection point, if one exists.
intersecting() [1/2]
template<class T > bool tr::intersecting (const Circle< T > & c1, const Circle< T > & c2) noexcept
Determines if two circles intersect.
Parameters
c1,c2 The circles to check for intersection.
Returns
True if the circles intersect, and false otherwise.
intersecting() [2/2]
template<class T1 , class T2 > bool tr::intersecting (const Rect2< T1 > & r1, const Rect2< T2 > & r2) noexcept
Determines if two rects intersect.
Parameters
r1,r2 The rects to check for intersection.
Returns
True if the rects intersect, and false otherwise.
Referenced by tr::intersecting(), and tr::intersecting().
inverse() [1/2]
template<std::size_t S, std::floating_point T> glm::vec< S, T > tr::inverse (const glm::vec< S, T > & vec) constexpr noexcept
Gets the inverse of a vector.
Parameters
vec The vector to invert.
Returns
The inverse vector.
Referenced by tr::inverse().
inverse() [2/2]
template<std::size_t S, std::integral T> glm::vec< S, double > tr::inverse (const glm::vec< S, T > & vec) constexpr noexcept
Gets the inverse of a vector.
Parameters
vec The vector to invert.
Returns
The inverse vector.
mirrorRepeat() [1/3]
template<int S, class T > glm::vec< S, T > tr::mirrorRepeat (const glm::vec< S, T > & v, const glm::vec< S, T > & min, const glm::vec< S, T > & max) noexcept
Performs a mirror repeat mapping.
Parameters
v The value to map.
min,max The bounds of the range.
Returns
v mirror mapped to [min, max).
mirrorRepeat() [2/3]
template<std::size_t S, class T > glm::vec< S, T > tr::mirrorRepeat (const glm::vec< S, T > & v, const Rect< S, T > & rect) noexcept
Performs a mirror repeat mapping of a vector on a rect.
Parameters
v The value to map.
rect The bounds of the range.
Returns
v mirror mapped to rect.
mirrorRepeat() [3/3]
template<Arithmetic T> T tr::mirrorRepeat (T v, T min, T max) noexcept
Performs a mirror repeat mapping.
Parameters
v The value to map.
min,max The bounds of the range.
Returns
v mirror mapped to [min, max).
Referenced by tr::mirrorRepeat(), tr::mirrorRepeat(), and tr::mirrorRepeat().
mod()
template<Arithmetic T1, Arithmetic T2> std::common_type_t< T1, T2 > tr::mod (T1 v, T2 mod) noexcept
Generic modulo operation.
Parameters
v The value to modulo.
mod The modulus.
Returns
The modulo of v by mod, standard promotion rules apply.
Referenced by tr::mod().
rotateAroundPoint2()
template<class T > glm::tmat4x4< T > tr::rotateAroundPoint2 (const glm::tmat4x4< T > & matrix, const glm::tvec2< T > & center, const Angle< T > & angle) noexcept
Applies a 2D rotation around a point to a matrix.
Parameters
matrix The matrix to apply the rotation to.
center The point to rotation around.
angle The rotation angle.
Returns
A matrix with the applied rotation.
Referenced by tr::rotateAroundPoint2().
rotateAroundPoint3()
template<class T > glm::tmat4x4< T > tr::rotateAroundPoint3 (const glm::tmat4x4< T > & matrix, const glm::tvec3< T > & center, const Angle< T > & angle, const glm::tvec3< T > & axis) noexcept
Applies a 3D rotation around a point to a matrix.
Parameters
matrix The matrix to apply the rotation to.
center The point to rotation around.
angle The rotation angle.
axis The axis to rotate around.
Returns
A matrix with the applied rotation.
Referenced by tr::rotateAroundPoint3().
scaleAroundPoint2()
template<class T > glm::tmat4x4< T > tr::scaleAroundPoint2 (const glm::tmat4x4< T > & matrix, const glm::tvec2< T > & center, const glm::tvec2< T > & scale) noexcept
Applies a 2D scaling around a point to a matrix.
Parameters
matrix The matrix to apply the scaling to.
center The point to scale around.
scale The scale factor.
Returns
A matrix with the applied scaling.
Referenced by tr::scaleAroundPoint2().
scaleAroundPoint3()
template<class T > glm::tmat4x4< T > tr::scaleAroundPoint3 (const glm::tmat4x4< T > & matrix, const glm::tvec3< T > & center, const glm::tvec3< T > & scale) noexcept
Applies a 3D scaling around a point to a matrix.
Parameters
matrix The matrix to apply the scaling to.
center The point to scale around.
scale The scale factor.
Returns
A matrix with the applied scaling.
Referenced by tr::scaleAroundPoint3().
segmentIntersect() [1/4]
template<std::floating_point T> std::optional< glm::tvec2< T > > tr::segmentIntersect (glm::tvec2< T > a1, Angle< T > th1, glm::tvec2< T > a2, glm::tvec2< T > b2) noexcept
Calculates the intersection point of a line with a line segment.
Parameters
a1,th1 Point and angle of the first line.
a2,b2 Delimiting points of the second line segment.
Returns
The intersection point, if one exists.
segmentIntersect() [2/4]
template<std::integral T> std::optional< glm::dvec2 > tr::segmentIntersect (glm::tvec2< T > a1, AngleD th1, glm::tvec2< T > a2, glm::tvec2< T > b2) noexcept
Calculates the intersection point of a line with a line segment.
Parameters
a1,th1 Point and angle of the first line.
a2,b2 Delimiting points of the second line segment.
Returns
The intersection point, if one exists.
segmentIntersect() [3/4]
template<std::floating_point T> std::optional< glm::tvec2< T > > tr::segmentIntersect (glm::tvec2< T > a1, glm::tvec2< T > b1, glm::tvec2< T > a2, glm::tvec2< T > b2) constexpr noexcept
Calculates the intersection point of two line segments.
Parameters
a1,b1 Delimiting points of the first line segment.
a2,b2 Delimiting points of the second line segment.
Returns
The intersection point, if one exists.
Referenced by tr::segmentIntersect(), tr::segmentIntersect(), and tr::segmentIntersect().
segmentIntersect() [4/4]
template<std::integral T> std::optional< glm::dvec2 > tr::segmentIntersect (glm::tvec2< T > a1, glm::tvec2< T > b1, glm::tvec2< T > a2, glm::tvec2< T > b2) constexpr noexcept
Calculates the intersection point of two line segments.
Parameters
a1,b1 Delimiting points of the first line segment.
a2,b2 Delimiting points of the second line segment.
Returns
The intersection point, if one exists.