libtr: Audio Buffer
Audio Buffer
Audio
Audio buffer class and related functionality.
Classes
struct tr::AudioBufferBadAlloc
Error thrown when allocating an audio buffer fails.
struct tr::UnsupportedAudioFile
Error thrown when an trying to load an unsupported audio file.
class tr::AudioBufferView
Non-owning audio buffer view.
class tr::AudioBuffer
Owning audio data buffer.
Enumerations
enum class tr::AudioFormat { tr::AudioFormat::MONO16 = 0x1101 , tr::AudioFormat::STEREO16 = 0x1103 }
Audio data format.
Functions
AudioBuffer tr::loadEmbeddedAudio (std::span< const std::byte > data)
Loads audio data from an embedded file to a buffer.
template<std::ranges::contiguous_range Range>
AudioBuffer tr::loadEmbeddedAudio (Range &&range)
Loads audio data from an embedded file to a buffer.
AudioBuffer tr::loadAudioFile (const std::filesystem::path &path)
Loads audio data from file to a buffer.
Detailed Description
Audio buffer class and related functionality.
Enumeration Type Documentation
AudioFormat
enum class tr::AudioFormat strong
Audio data format.
Enumerator
MONO16
1-channel, 16-bit audio.
STEREO16
2-channel, 16-bit audio.
Function Documentation
loadEmbeddedAudio() [1/2]
AudioBuffer tr::loadEmbeddedAudio (std::span< const std::byte > data)
Loads audio data from an embedded file to a buffer.
Exception Safety
Strong exception guarantee.
Exceptions
AudioBufferBadAlloc If allocating the buffer fails.
Parameters
[in] data
The embedded file data.
Precondition
data is assumed to always be a valid audio file.
Returns
An audio buffer loaded with data from the embedded file.
Referenced by loadEmbeddedAudio(), and loadEmbeddedAudio().
loadEmbeddedAudio() [2/2]
template<std::ranges::contiguous_range Range> AudioBuffer tr::loadEmbeddedAudio (Range && range)
Loads audio data from an embedded file to a buffer.
Exception Safety
Strong exception guarantee.
Exceptions
AudioBufferBadAlloc If allocating the buffer fails.
Parameters
[in] range
The embedded file range.
Precondition
range is assumed to always be a valid audio file.
Returns
An audio buffer loaded with data from the embedded file.
loadAudioFile()
AudioBuffer tr::loadAudioFile (const std::filesystem::path & path)
Loads audio data from file to a buffer.
Exception Safety
Strong exception guarantee.
Exceptions
FileNotFound If the file isn't found.
FileOpenError If opening the file fails.
UnsupportedAudioFile If the file is an unsupported or invalid format.
std::bad_alloc If allocating a buffer for reading the data fails.
AudioBufferBadAlloc If allocating the buffer fails.
Parameters
[in] path The path to an audio file.
Returns
An audio buffer loaded with data from the file.
Referenced by loadAudioFile().