libtr: Ranges
Ranges
Miscellaneous
Custom range functionality.
Functions
template<StandardLayoutRange T>
auto tr::rangeBytes (const T &range) noexcept
Gets a view of a contiguous range as a span of immutable bytes.
template<StandardLayout T>
std::span< const std::byte, sizeof(T)> tr::asBytes (const T &object) noexcept
Gets a view of an object as a span of immutable bytes.
template<StandardLayoutRange T>
auto tr::rangeMutBytes (T &range) noexcept
Gets a view of a contiguous range as a span of mutable bytes.
template<StandardLayout T>
std::span< std::byte, sizeof(T)> tr::asMutBytes (T &object) noexcept
Gets a view of an object as a span of mutable bytes.
template<StandardLayout T, std::size_t S>
auto tr::asMutObjects (std::span< std::byte, S > bytes) noexcept
Reinterprets a span of mutable bytes as a span of objects.
template<StandardLayout T, std::size_t S>
auto tr::asObjects (std::span< const std::byte, S > bytes) noexcept
Reinterprets a span of immutable bytes as a span of const objects.
template<class R>
constexpr auto tr::project (auto R::*ptr) noexcept
Creates an adaptor for a transformed view over a range as a range of one of its members.
template<std::ranges::range R>
constexpr auto tr::project (R &&range, auto std::ranges::range_value_t< R >::*ptr) noexcept
Creates a transformed view over a range as a range of one of its members.
Detailed Description
Custom range functionality.
Function Documentation
rangeBytes()
template<StandardLayoutRange T> auto tr::rangeBytes (const T & range) noexcept
Gets a view of a contiguous range as a span of immutable bytes.
Template Parameters
T A type that fulfills StandardLayoutRange.
Parameters
[in] range The range to get a byte view of.
Returns
A span over the range's bytes.
Referenced by tr::BitmapView::BitmapView(), tr::Cursor::Cursor(), tr::VertexBuffer::VertexBuffer(), loadEmbeddedAudio(), loadEmbeddedBitmap(), loadEmbeddedShader(), tr::VertexBuffer::set(), tr::ShaderBuffer::setArray(), tr::ShaderBuffer::setHeader(), and tr::VertexBuffer::setRegion().
asBytes()
template<StandardLayout T> std::span< const std::byte, sizeof(T)> tr::asBytes (const T & object) noexcept
Gets a view of an object as a span of immutable bytes.
Template Parameters
T A standard layout type.
Parameters
[in] object The object to get a byte view of.
Returns
A span over the object's bytes.
Referenced by tr::ShaderBuffer::setHeader().
rangeMutBytes()
template<StandardLayoutRange T> auto tr::rangeMutBytes (T & range) noexcept
Gets a view of a contiguous range as a span of mutable bytes.
Template Parameters
T A type that fulfills StandardLayoutRange.
Parameters
[in] range The range to get a byte view of.
Returns
A mutable span over the range's bytes.
asMutBytes()
template<StandardLayout T> std::span< std::byte, sizeof(T)> tr::asMutBytes (T & object) noexcept
Gets a view of an object as a span of mutable bytes.
Template Parameters
T A standard layout type.
Parameters
[in] object The object to get a byte view of.
Returns
A mutable span over the object's bytes.
asMutObjects()
template<StandardLayout T, std::size_t S> auto tr::asMutObjects (std::span< std::byte, S > bytes) noexcept
Reinterprets a span of mutable bytes as a span of objects.
Precondition
The span must be an integer multiple of the size of the object being cast into. If the span has a static length, the function will fail to compile, and if the span has a dynamic length, a failed assertion may be triggered.
Parameters
[in] bytes The byte span to reinterpret.
Returns
A mutable span over objects.
asObjects()
template<StandardLayout T, std::size_t S> auto tr::asObjects (std::span< const std::byte, S > bytes) noexcept
Reinterprets a span of immutable bytes as a span of const objects.
Precondition
The span must be an integer multiple of the size of the object being cast into. If the span has a static length, the function will fail to compile, and if the span has a dynamic length, a failed assertion may be triggered.
Parameters
[in] bytes The byte span to reinterpret.
Returns
A span over const objects.
project() [1/2]
template<class R> auto tr::project (auto R::* ptr) constexpr noexcept
Creates an adaptor for a transformed view over a range as a range of one of its members.
Parameters
[in] ptr A class member pointer.
Returns
An adaptor for the projection transformer.
project() [2/2]
template<std::ranges::range R> auto tr::project (R && range, auto std::ranges::range_value_t< R >::* ptr) constexpr noexcept
Creates a transformed view over a range as a range of one of its members.
Template Parameters
R A range type.
Parameters
[in] range The range to transform.
[in] ptr A class member pointer.
Returns
The transformed view.