libtr: RNG
RNG
Miscellaneous
Random number generation functionality.
Classes
class tr::Xorshiftr128p
Xorshiftr128+ random number generator.
Functions
std::uint64_t tr::generateRandomSeed () noexcept
Generates a random seed.
constexpr bool tr::randb (Xorshiftr128p &rng) noexcept
Generates a random boolean value.
template<std::integral T>
constexpr T tr::rand (Xorshiftr128p &rng) noexcept
Generates a random integral value.
template<std::integral T>
constexpr T tr::rand (Xorshiftr128p &rng, T max) noexcept
Generates a random integral value in the range [0, max).
template<std::integral T>
constexpr T tr::rand (Xorshiftr128p &rng, T min, T max) noexcept
Generates a random integral value in the range [min, max).
Detailed Description
Random number generation functionality.
Function Documentation
generateRandomSeed()
std::uint64_t tr::generateRandomSeed () noexcept
Generates a random seed.
Returns
A random boolean value.
randb()
bool tr::randb (Xorshiftr128p & rng) constexpr noexcept
Generates a random boolean value.
Parameters
rng The random number generator to use.
Returns
A random boolean value.
Referenced by randb().
rand() [1/3]
template<std::integral T> T tr::rand (Xorshiftr128p & rng) constexpr noexcept
Generates a random integral value.
Generates a random angle value in the range [0tr, 1tr).
Generates a random floating point value in the range [0, 1).
Parameters
rng The random number generator to use.
Returns
A random integral value.
Parameters
rng The random number generator to use.
Returns
A random floating point value in the range [0, 1).
Parameters
rng The random number generator to use.
Returns
A random angle value in the range [0tr, 1tr).
Referenced by rand(), rand(), and rand().
rand() [2/3]
template<std::integral T> T tr::rand (Xorshiftr128p & rng, T max) constexpr noexcept
Generates a random integral value in the range [0, max).
Generates a random angle value in the range [0, max).
Generates a random floating point value in the range [0, max).
Parameters
rng The random number generator to use.
max
The upper boundary for the generated value.
Precondition
max cannot be 0.
Returns
A random integral value in the range [0, max).
Parameters
rng The random number generator to use.
max The upper boundary for the generated value.
Returns
A random floating point value in the range [0, max).
Parameters
rng The random number generator to use.
max The upper boundary for the generated value.
Returns
A random angle value in the range [0tr, max).
rand() [3/3]
template<std::integral T> T tr::rand (Xorshiftr128p & rng, T min, T max) constexpr noexcept
Generates a random integral value in the range [min, max).
Generates a random angle value in the range [min, max).
Generates a random floating point value in the range [min, max).
Precondition
(min - max) cannot be 0.
Parameters
rng The random number generator to use.
min The lower boundary for the generated value.
max The upper boundary for the generated value.
Returns
A random integral value in the range [min, max).
Precondition
(min - max) cannot be 0.
Parameters
rng The random number generator to use.
min The lower boundary for the generated value.
max The upper boundary for the generated value.
Returns
A random floating point value in the range [min, max).
Precondition
(min - max) cannot be 0.
Parameters
rng The random number generator to use.
min The lower boundary for the generated value.
max The upper boundary for the generated value.
Returns
A random angle value in the range [min, max).