libtr: Streams
Streams
Miscellaneous
Custom I/O stream functionality.
Concepts
concept tr::BinaryFlushableContainer
Concept that denotes a binaryFlush-compatible container.
Classes
class tr::FileError
Generic file error base exception type.
struct tr::FileNotFound
File not found exception.
struct tr::FileOpenError
File opening error exception.
Functions
std::ofstream tr::openFileW (const std::filesystem::path &path, std::ios::openmode openmode=std::ios::in)
Opens a file for writing with extra checks.
std::ifstream tr::openFileR (const std::filesystem::path &path, std::ios::openmode openmode=std::ios::out)
Opens a file for reading with extra checks.
template<StandardLayout T>
void tr::readBinary (std::istream &is, T &out)
Reads binary data into an existing object.
template<StandardLayout T>
T tr::readBinary (std::istream &is)
Reads binary data into a new object.
template<StandardLayoutRange Range>
void tr::readBinaryRange (std::istream &is, Range &&out)
Reads binary data into a contiguous range.
template<std::output_iterator< char > It>
void tr::flushBinary (std::istream &is, It out)
Flushes the rest of the stream into an output iterator.
template<BinaryFlushableContainer Container>
Container tr::flushBinary (std::istream &is)
Flushes the rest of the stream into a container.
template<StandardLayout T>
void tr::writeBinary (std::ostream &os, const T &in)
Writes an object's binary data to stream.
template<StandardLayoutRange Range>
void tr::writeBinaryRange (std::ostream &os, const Range &range)
Writes a contiguous range's binary data to stream.
void tr::writeBinary (std::ostream &os, const char *cstr)
Writes a C-string to stream.
Detailed Description
Custom I/O stream functionality.
Function Documentation
openFileW()
std::ofstream tr::openFileW (const std::filesystem::path & path, std::ios::openmode openmode = std::ios::in)
Opens a file for writing with extra checks.
Exception Safety
Strong exception guarantee.
Exceptions
FileOpenError If the file at path cannot be opened.
Parameters
[in] path The file path. Must be a valid, writable file.
[in] openmode std::ostream openmode arguments.
Returns
An output file stream.
Referenced by openFileW().
openFileR()
std::ifstream tr::openFileR (const std::filesystem::path & path, std::ios::openmode openmode = std::ios::out)
Opens a file for reading with extra checks.
Exception Safety
Strong exception guarantee.
Exceptions
FileNotFound If the file path does not lead to a regular file.
FileOpenError If the file at path cannot be opened.
Parameters
[in] path The file path. Must be a valid, readable file.
[in] openmode std::istream openmode arguments.
Returns
An input file stream.
Referenced by openFileR().
readBinary() [1/2]
template<StandardLayout T> void tr::readBinary (std::istream & is, T & out)
Reads binary data into an existing object.
Exceptions
std::ios_base::failure If the stream throws an error.
Parameters
[in] is The input stream.
[out] out The output object.
Referenced by readBinary(), readBinary(), and writeBinary().
readBinary() [2/2]
template<StandardLayout T> T tr::readBinary (std::istream & is)
Reads binary data into a new object.
Exceptions
std::ios_base::failure If the stream throws an error.
Parameters
[in] is The input stream.
Returns
A new object with the extracted value.
readBinaryRange()
template<StandardLayoutRange Range> void tr::readBinaryRange (std::istream & is, Range && out)
Reads binary data into a contiguous range.
Exceptions
std::ios_base::failure If the stream throws an error.
Parameters
[in] is The input stream.
[out] out The output range.
Referenced by readBinaryRange().
flushBinary() [1/2]
template<std::output_iterator< char > It> void tr::flushBinary (std::istream & is, It out)
Flushes the rest of the stream into an output iterator.
Exceptions
std::ios_base::failure If the stream throws an error.
Parameters
[in] is The input stream.
[out] out The output iterator.
Referenced by flushBinary(), and flushBinary().
flushBinary() [2/2]
template<BinaryFlushableContainer Container> Container tr::flushBinary (std::istream & is)
Flushes the rest of the stream into a container.
Container must satisfy BinaryFlushableContainer.
Exceptions
std::ios_base::failure If the stream throws an error.
std::bad_alloc If container construction fails.
Parameters
[in] is The input stream.
Returns
A container with the rest of the stream data.
writeBinary() [1/2]
template<StandardLayout T> void tr::writeBinary (std::ostream & os, const T & in)
Writes an object's binary data to stream.
Exceptions
std::ios_base::failure If the stream throws an error.
Parameters
[out] os The output stream.
[in] in The input object.
Referenced by writeBinary(), and writeBinary().
writeBinaryRange()
template<StandardLayoutRange Range> void tr::writeBinaryRange (std::ostream & os, const Range & range)
Writes a contiguous range's binary data to stream.
Exceptions
std::ios_base::failure If the stream throws an error.
Parameters
[out] os The output stream.
[in] range The input range.
Referenced by writeBinaryRange().
writeBinary() [2/2]
void tr::writeBinary (std::ostream & os, const char * cstr) inline
Writes a C-string to stream.
Exceptions
std::ios_base::failure If the stream throws an error.
Parameters
[out] os The output stream.
[in] cstr The input string.