libtr: Bitmaps
Bitmaps
System
Bitmap classes and related functionality.
Classes
struct tr::BitmapBadAlloc
Error thrown when bitmap allocation fails.
struct tr::BitmapLoadError
Error thrown when bitmap loading fails.
struct tr::BitmapSaveError
Error thrown when bitmap saving fails.
class tr::SubBitmap
View over a rectangular region of a bitmap.
class tr::SubBitmap::PixelRef
Read-only reference to a bitmap pixel.
class tr::SubBitmap::Iterator
Immutable bitmap pixel iterator.
class tr::BitmapView
Non-owning view over bitmap data.
class tr::BitmapFormat
Bitmap format information.
class tr::Bitmap
Class containing owned bitmap data.
class tr::Bitmap::PixelRef
Mutable reference to a bitmap pixel.
class tr::Bitmap::MutIt
Mutable pixel iterator.
Functions
Bitmap tr::createCheckerboard (glm::ivec2 size)
Creates a bitmap with the missing texture checkerboard pattern.
Bitmap tr::loadEmbeddedBitmap (std::span< const std::byte > data)
Loads an embedded bitmap file.
template<std::ranges::contiguous_range Range>
Bitmap tr::loadEmbeddedBitmap (Range &&range)
Loads an embedded bitmap file.
Bitmap tr::loadBitmapFile (const std::filesystem::path &path)
Loads a bitmap from file (BMP/PNG/JPG/QOI).
Detailed Description
Bitmap classes and related functionality.
Function Documentation
createCheckerboard()
Bitmap tr::createCheckerboard (glm::ivec2 size)
Creates a bitmap with the missing texture checkerboard pattern.
Exceptions
BitmapBadAlloc If allocating the bitmap fails.
Parameters
[in] size The size of the bitmap.
Returns
A bitmap with the missing texture checkerboard pattern.
Referenced by createCheckerboard().
loadEmbeddedBitmap() [1/2]
Bitmap tr::loadEmbeddedBitmap (std::span< const std::byte > data)
Loads an embedded bitmap file.
Exception Safety
Strong exception guarantee.
Exceptions
BitmapBadAlloc If allocating the bitmap fails.
Parameters
[in] data
The embedded file data.
Precondition
data is assumed to always be a valid bitmap file.
Returns
A bitmap loaded with data from the embedded file.
Referenced by loadEmbeddedBitmap(), and loadEmbeddedBitmap().
loadEmbeddedBitmap() [2/2]
template<std::ranges::contiguous_range Range> Bitmap tr::loadEmbeddedBitmap (Range && range)
Loads an embedded bitmap file.
Exception Safety
Strong exception guarantee.
Exceptions
BitmapBadAlloc If allocating the bitmap fails.
Parameters
[in] range
The embedded file data.
Precondition
range is assumed to always be a valid bitmap file.
Returns
A bitmap loaded with data from the embedded file.
loadBitmapFile()
Bitmap tr::loadBitmapFile (const std::filesystem::path & path)
Loads a bitmap from file (BMP/PNG/JPG/QOI).
Exception Safety
Strong exception guarantee.
Exceptions
FileNotFound If the file isn't found.
BitmapLoadError If loading the bitmap fails.
Parameters
[in] path The path to the bitmap file.
Returns
A bitmap loaded with data from the file.
Referenced by loadBitmapFile().