libtr: Angles
Angles
Miscellaneous
Angle datatype and related functionality.
Namespaces
namespace tr::angle_literals
Inline namespace containing angle value literals.
Concepts
concept tr::AngleBase
Concept denoting a valid angle base type.
Classes
class tr::Angle< T >
Angular value type.
Typedefs
using tr::AngleF = Angle<float>
Shorthand for a float angle.
using tr::AngleD = Angle<double>
Shorthand for a double angle.
using tr::AngleL = Angle<long double>
Shorthand for a long double angle.
Functions
template<Arithmetic T>
constexpr auto tr::rads (T th) noexcept
Converts a numeric value into an angle value.
template<Arithmetic T>
constexpr auto tr::degs (T th) noexcept
Converts a numeric value into an angle value.
template<Arithmetic T>
constexpr auto tr::turns (T th) noexcept
Converts a numeric value into an angle value.
template<Arithmetic T>
constexpr auto tr::asin (T sin) noexcept
Converts a sine value into an angle value.
template<Arithmetic T>
constexpr auto tr::acos (T cos) noexcept
Converts a cosine value into an angle value.
template<Arithmetic T>
constexpr auto tr::atan (T tan) noexcept
Converts a tangent value into an angle value.
template<Arithmetic T>
constexpr auto tr::atan2 (T y, T x) noexcept
Converts tangent x and y values into an angle value.
Detailed Description
Angle datatype and related functionality.
Typedef Documentation
AngleF
using tr::AngleF = Angle<float>
Shorthand for a float angle.
AngleD
using tr::AngleD = Angle<double>
Shorthand for a double angle.
AngleL
using tr::AngleL = Angle<long double>
Shorthand for a long double angle.
Function Documentation
rads()
template<Arithmetic T> auto tr::rads (T th) constexpr noexcept
Converts a numeric value into an angle value.
Template Parameters
T An arithmetic type. Integer values return an AngleD value, while floating points return an angle of the same base type.
Parameters
[in] th The numeric value in radians.
Returns
An angle value.
Referenced by rads().
degs()
template<Arithmetic T> auto tr::degs (T th) constexpr noexcept
Converts a numeric value into an angle value.
Template Parameters
T An arithmetic type. Integer values return an AngleD value, while floating points return an angle of the same base type.
Parameters
[in] th The numeric value in degrees.
Returns
An angle value.
Referenced by degs().
turns()
template<Arithmetic T> auto tr::turns (T th) constexpr noexcept
Converts a numeric value into an angle value.
Template Parameters
T An arithmetic type. Integer values return an AngleD value, while floating points return an angle of the same base type.
Parameters
[in] th The numeric value in turns.
Returns
An angle value.
Referenced by turns().
asin()
template<Arithmetic T> auto tr::asin (T sin) constexpr noexcept
Converts a sine value into an angle value.
Template Parameters
T An arithmetic type. Integer values return an AngleD value, while floating points return an angle of the same base type.
Parameters
[in] sin The value of the sine.
Returns
An angle value as if produced by tr::rads(std::asin(sin)).
Referenced by asin().
acos()
template<Arithmetic T> auto tr::acos (T cos) constexpr noexcept
Converts a cosine value into an angle value.
Template Parameters
T An arithmetic type. Integer values return an AngleD value, while floating points return an angle of the same base type.
Parameters
[in] cos The value of the cosine.
Returns
An angle value as if produced by tr::rads(std::acos(sin)).
Referenced by acos().
atan()
template<Arithmetic T> auto tr::atan (T tan) constexpr noexcept
Converts a tangent value into an angle value.
Template Parameters
T An arithmetic type. Integer values return an AngleD value, while floating points return an angle of the same base type.
Parameters
[in] tan The value of the tangent.
Returns
An angle value as if produced by tr::rads(std::atan(sin)).
Referenced by atan().
atan2()
template<Arithmetic T> auto tr::atan2 (T y, T x) constexpr noexcept
Converts tangent x and y values into an angle value.
Template Parameters
T An arithmetic type. Integer values return an AngleD value, while floating points return an angle of the same base type.
Parameters
[in] y,x Tangent values.
Returns
An angle value as if produced by tr::rads(std::atan2(y, x)).
Referenced by atan2().