var hierarchy =
[
    [ "tr::ABGR_Ui16_1_5_5_5", "structtr_1_1ABGR__Ui16__1__5__5__5.html", null ],
    [ "tr::ABGR_Ui16_4_4_4_4", "structtr_1_1ABGR__Ui16__4__4__4__4.html", null ],
    [ "tr::ABGR_Ui32_2_10_10_10", "structtr_1_1ABGR__Ui32__2__10__10__10.html", null ],
    [ "tr::Angle< T >", "classtr_1_1Angle.html", null ],
    [ "tr::ARGB_Ui16_1_5_5_5", "structtr_1_1ARGB__Ui16__1__5__5__5.html", null ],
    [ "tr::ARGB_Ui16_4_4_4_4", "structtr_1_1ARGB__Ui16__4__4__4__4.html", null ],
    [ "tr::ARGB_Ui32_2_10_10_10", "structtr_1_1ARGB__Ui32__2__10__10__10.html", null ],
    [ "tr::AudioBuffer", "classtr_1_1AudioBuffer.html", null ],
    [ "tr::AudioBufferView", "classtr_1_1AudioBufferView.html", null ],
    [ "tr::AudioSystem", "classtr_1_1AudioSystem.html", null ],
    [ "tr::B< T >", "structtr_1_1B.html", null ],
    [ "tr::BasicFramebuffer", "classtr_1_1BasicFramebuffer.html", [
      [ "tr::Backbuffer", "classtr_1_1Backbuffer.html", null ],
      [ "tr::Framebuffer", "classtr_1_1Framebuffer.html", null ]
    ] ],
    [ "tr::Benchmark", "classtr_1_1Benchmark.html", null ],
    [ "tr::BGR< T >", "structtr_1_1BGR.html", null ],
    [ "tr::BGR_Ui16_5_6_5", "structtr_1_1BGR__Ui16__5__6__5.html", null ],
    [ "tr::BGR_Ui8_3_3_2", "structtr_1_1BGR__Ui8__3__3__2.html", null ],
    [ "tr::BGRA< T >", "structtr_1_1BGRA.html", null ],
    [ "tr::BGRA_Ui16_4_4_4_4", "structtr_1_1BGRA__Ui16__4__4__4__4.html", null ],
    [ "tr::BGRA_Ui16_5_5_5_1", "structtr_1_1BGRA__Ui16__5__5__5__1.html", null ],
    [ "tr::BGRA_Ui32_10_10_10_2", "structtr_1_1BGRA__Ui32__10__10__10__2.html", null ],
    [ "tr::Bitmap", "classtr_1_1Bitmap.html", null ],
    [ "tr::BitmapFormat", "classtr_1_1BitmapFormat.html", null ],
    [ "tr::BitmapView", "classtr_1_1BitmapView.html", null ],
    [ "tr::BlendMode", "structtr_1_1BlendMode.html", null ],
    [ "tr::Circle< T >", "structtr_1_1Circle.html", null ],
    [ "tr::ClrVtx2", "structtr_1_1ClrVtx2.html", null ],
    [ "tr::ColorCaster< T >", "structtr_1_1ColorCaster.html", null ],
    [ "tr::ColorCaster< HSV >", "structtr_1_1ColorCaster_3_01HSV_01_4.html", null ],
    [ "tr::Colors", "structtr_1_1Colors.html", null ],
    [ "tr::Cursor", "classtr_1_1Cursor.html", null ],
    [ "tr::CustomEventBase", "structtr_1_1CustomEventBase.html", null ],
    [ "Deleter", null, [
      [ "tr::Handle< unsigned int, 0, Deleter >", "classtr_1_1Handle.html", null ],
      [ "tr::Handle< unsigned int, -1U, Deleter >", "classtr_1_1Handle.html", null ],
      [ "tr::Handle< bool, false, SDLDeleter >", "classtr_1_1Handle.html", null ],
      [ "tr::Handle< T, EmptyValue, Deleter >", "classtr_1_1Handle.html", null ]
    ] ],
    [ "tr::DisplayInfo", "classtr_1_1DisplayInfo.html", null ],
    [ "tr::DisplayMode", "structtr_1_1DisplayMode.html", null ],
    [ "tr::Event", "classtr_1_1Event.html", null ],
    [ "tr::EventQueue", "classtr_1_1EventQueue.html", null ],
    [ "std::exception", null, [
      [ "std::bad_alloc", null, [
        [ "tr::AudioBufferBadAlloc", "structtr_1_1AudioBufferBadAlloc.html", null ],
        [ "tr::BitmapBadAlloc", "structtr_1_1BitmapBadAlloc.html", null ],
        [ "tr::CursorBadAlloc", "structtr_1_1CursorBadAlloc.html", null ],
        [ "tr::GraphicsBufferBadAlloc", "structtr_1_1GraphicsBufferBadAlloc.html", null ],
        [ "tr::GraphicsBufferMapBadAlloc", "structtr_1_1GraphicsBufferMapBadAlloc.html", null ],
        [ "tr::RenderbufferBadAlloc", "structtr_1_1RenderbufferBadAlloc.html", null ],
        [ "tr::TextureBadAlloc", "structtr_1_1TextureBadAlloc.html", null ]
      ] ],
      [ "std::runtime_error", null, [
        [ "tr::AudioSystemInitializationError", "structtr_1_1AudioSystemInitializationError.html", null ],
        [ "tr::SDLError", "structtr_1_1SDLError.html", [
          [ "tr::EventPushError", "structtr_1_1EventPushError.html", null ],
          [ "tr::TTFontError", "structtr_1_1TTFontError.html", null ],
          [ "tr::WindowError", "structtr_1_1WindowError.html", null ]
        ] ],
        [ "tr::WindowOpenError", "structtr_1_1WindowOpenError.html", null ]
      ] ],
      [ "tr::ExeDirInitError", "structtr_1_1ExeDirInitError.html", null ],
      [ "tr::FileError", "classtr_1_1FileError.html", [
        [ "tr::BitmapLoadError", "structtr_1_1BitmapLoadError.html", null ],
        [ "tr::BitmapSaveError", "structtr_1_1BitmapSaveError.html", null ],
        [ "tr::FileNotFound", "structtr_1_1FileNotFound.html", null ],
        [ "tr::FileOpenError", "structtr_1_1FileOpenError.html", null ],
        [ "tr::ShaderLoadError", "structtr_1_1ShaderLoadError.html", null ],
        [ "tr::TTFontLoadError", "structtr_1_1TTFontLoadError.html", null ],
        [ "tr::UnsupportedAudioFile", "structtr_1_1UnsupportedAudioFile.html", null ]
      ] ],
      [ "tr::UserDirInitError", "structtr_1_1UserDirInitError.html", null ]
    ] ],
    [ "Fs...", null, [
      [ "tr::Overloaded< Fs >", "structtr_1_1Overloaded.html", null ]
    ] ],
    [ "tr::G< T >", "structtr_1_1G.html", null ],
    [ "tr::TTFont::Glyph", "structtr_1_1TTFont_1_1Glyph.html", null ],
    [ "tr::GraphicsBuffer", "classtr_1_1GraphicsBuffer.html", [
      [ "tr::ShaderBuffer", "classtr_1_1ShaderBuffer.html", null ]
    ] ],
    [ "tr::GraphicsBufferMap", "classtr_1_1GraphicsBufferMap.html", [
      [ "tr::IndexBufferMap", "classtr_1_1IndexBufferMap.html", null ]
    ] ],
    [ "tr::GraphicsContext", "classtr_1_1GraphicsContext.html", null ],
    [ "tr::GraphicsProperties", "structtr_1_1GraphicsProperties.html", null ],
    [ "tr::HSV", "structtr_1_1HSV.html", null ],
    [ "tr::IndexBuffer", "classtr_1_1IndexBuffer.html", null ],
    [ "tr::SubBitmap::Iterator", "classtr_1_1SubBitmap_1_1Iterator.html", null ],
    [ "tr::Keyboard", "classtr_1_1Keyboard.html", null ],
    [ "tr::Keycode", "classtr_1_1Keycode.html", null ],
    [ "tr::KeyDownEvent", "structtr_1_1KeyDownEvent.html", null ],
    [ "tr::KeyInfo", "structtr_1_1KeyInfo.html", null ],
    [ "tr::KeyUpEvent", "structtr_1_1KeyUpEvent.html", null ],
    [ "tr::Listener", "classtr_1_1Listener.html", null ],
    [ "tr::TTFont::MeasureResult", "structtr_1_1TTFont_1_1MeasureResult.html", null ],
    [ "tr::Mouse", "classtr_1_1Mouse.html", null ],
    [ "tr::MouseDownEvent", "structtr_1_1MouseDownEvent.html", null ],
    [ "tr::MouseMotionEvent", "structtr_1_1MouseMotionEvent.html", null ],
    [ "tr::MouseUpEvent", "structtr_1_1MouseUpEvent.html", null ],
    [ "tr::MouseWheelEvent", "structtr_1_1MouseWheelEvent.html", null ],
    [ "tr::Bitmap::MutIt", "classtr_1_1Bitmap_1_1MutIt.html", null ],
    [ "tr::NoEmptyHandleCheck", "structtr_1_1NoEmptyHandleCheck.html", null ],
    [ "tr::Orientation", "structtr_1_1Orientation.html", null ],
    [ "tr::OwningShaderPipeline", "classtr_1_1OwningShaderPipeline.html", null ],
    [ "tr::Bitmap::PixelRef", "classtr_1_1Bitmap_1_1PixelRef.html", null ],
    [ "tr::SubBitmap::PixelRef", "classtr_1_1SubBitmap_1_1PixelRef.html", null ],
    [ "tr::Positions", "structtr_1_1Positions.html", null ],
    [ "tr::R< T >", "structtr_1_1R.html", null ],
    [ "tr::Rect< S, T >", "structtr_1_1Rect.html", null ],
    [ "tr::Rect< int >", "structtr_1_1Rect.html", null ],
    [ "tr::Renderbuffer", "classtr_1_1Renderbuffer.html", null ],
    [ "tr::RG< T >", "structtr_1_1RG.html", null ],
    [ "tr::RGB< T >", "structtr_1_1RGB.html", null ],
    [ "tr::RGB_Ui16_5_6_5", "structtr_1_1RGB__Ui16__5__6__5.html", null ],
    [ "tr::RGB_Ui8_2_3_3", "structtr_1_1RGB__Ui8__2__3__3.html", null ],
    [ "tr::RGBA< T >", "structtr_1_1RGBA.html", null ],
    [ "tr::RGBA< std::uint8_t >", "structtr_1_1RGBA.html", null ],
    [ "tr::RGBA_Ui16_4_4_4_4", "structtr_1_1RGBA__Ui16__4__4__4__4.html", null ],
    [ "tr::RGBA_Ui16_5_5_5_1", "structtr_1_1RGBA__Ui16__5__5__5__1.html", null ],
    [ "tr::RGBA_Ui32_10_10_10_2", "structtr_1_1RGBA__Ui32__10__10__10__2.html", null ],
    [ "tr::Sampler", "classtr_1_1Sampler.html", null ],
    [ "tr::Scancode", "classtr_1_1Scancode.html", null ],
    [ "tr::Shader", "classtr_1_1Shader.html", null ],
    [ "tr::ShaderPipeline", "classtr_1_1ShaderPipeline.html", null ],
    [ "tr::Stopwatch", "classtr_1_1Stopwatch.html", null ],
    [ "tr::SubBitmap", "classtr_1_1SubBitmap.html", null ],
    [ "tr::TextEditEvent", "structtr_1_1TextEditEvent.html", null ],
    [ "tr::TextInputEvent", "structtr_1_1TextInputEvent.html", null ],
    [ "tr::Texture", "classtr_1_1Texture.html", [
      [ "tr::ArrayTexture1D", "structtr_1_1ArrayTexture1D.html", null ],
      [ "tr::ArrayTexture2D", "structtr_1_1ArrayTexture2D.html", null ],
      [ "tr::Texture1D", "structtr_1_1Texture1D.html", null ],
      [ "tr::Texture2D", "structtr_1_1Texture2D.html", null ],
      [ "tr::Texture3D", "structtr_1_1Texture3D.html", null ]
    ] ],
    [ "tr::TextureUnit", "classtr_1_1TextureUnit.html", null ],
    [ "tr::TexVtx2", "structtr_1_1TexVtx2.html", null ],
    [ "tr::TickEvent", "structtr_1_1TickEvent.html", null ],
    [ "tr::Timer", "classtr_1_1Timer.html", null ],
    [ "tr::TintVtx2", "structtr_1_1TintVtx2.html", null ],
    [ "tr::TTFont", "classtr_1_1TTFont.html", null ],
    [ "tr::Utf8ConstIt", "classtr_1_1Utf8ConstIt.html", null ],
    [ "tr::UVs", "structtr_1_1UVs.html", null ],
    [ "std::variant", null, [
      [ "tr::WindowEvent", "structtr_1_1WindowEvent.html", null ]
    ] ],
    [ "tr::VertexAttributeD", "structtr_1_1VertexAttributeD.html", null ],
    [ "tr::VertexAttributeF", "structtr_1_1VertexAttributeF.html", null ],
    [ "tr::VertexAttributeI", "structtr_1_1VertexAttributeI.html", null ],
    [ "tr::VertexBuffer", "classtr_1_1VertexBuffer.html", null ],
    [ "tr::VertexFormat", "classtr_1_1VertexFormat.html", null ],
    [ "tr::Window", "classtr_1_1Window.html", null ],
    [ "tr::WindowCloseEvent", "structtr_1_1WindowCloseEvent.html", null ],
    [ "tr::WindowEnterEvent", "structtr_1_1WindowEnterEvent.html", null ],
    [ "tr::WindowExposeEvent", "structtr_1_1WindowExposeEvent.html", null ],
    [ "tr::WindowGainFocusEvent", "structtr_1_1WindowGainFocusEvent.html", null ],
    [ "tr::WindowHideEvent", "structtr_1_1WindowHideEvent.html", null ],
    [ "tr::WindowLeaveEvent", "structtr_1_1WindowLeaveEvent.html", null ],
    [ "tr::WindowLoseFocusEvent", "structtr_1_1WindowLoseFocusEvent.html", null ],
    [ "tr::WindowMaximizeEvent", "structtr_1_1WindowMaximizeEvent.html", null ],
    [ "tr::WindowMinimizeEvent", "structtr_1_1WindowMinimizeEvent.html", null ],
    [ "tr::WindowMotionEvent", "structtr_1_1WindowMotionEvent.html", null ],
    [ "tr::WindowResizeEvent", "structtr_1_1WindowResizeEvent.html", null ],
    [ "tr::WindowRestoreEvent", "structtr_1_1WindowRestoreEvent.html", null ],
    [ "tr::WindowShowEvent", "structtr_1_1WindowShowEvent.html", null ],
    [ "tr::WindowSizeChangeEvent", "structtr_1_1WindowSizeChangeEvent.html", null ]
];