libtr: tr::ArrayTexture1D Struct Reference
tr::ArrayTexture1D Struct Reference
System » Graphics » Textures
One-dimensional array texture.
Public Member Functions
ArrayTexture1D (int size, int layers, bool mipmapped=false, TextureFormat format=TextureFormat::RGBA8)
Allocates an uninitialized 1D array texture.
ArrayTexture1D (SubBitmap bitmap, bool mipmapped=false, TextureFormat format=TextureFormat::RGBA8)
Constructs a 1D array texture with data uploaded from a bitmap.
int size () const noexcept
Gets the size of the texture.
int layers () const noexcept
Gets the number of layers in the texture.
void setRegion (glm::ivec2 tl, SubBitmap bitmap) noexcept
Sets a region of the texture as if it were a 2D texture.
Public Member Functions inherited from tr::Texture
TextureFormat format () const noexcept
Gets the format of the texture.
void setSwizzle (Swizzle r, Swizzle g, Swizzle b, Swizzle a) noexcept
Sets the swizzle parameters of the texture.
void setMinFilter (MinFilter filter) noexcept
Sets the minifying filter used by the texture sampler.
void setMagFilter (MagFilter filter) noexcept
Sets the magnifying filter used by the texture sampler.
void setMinLOD (int lod) noexcept
Sets the minimum allowed level-of-detail parameter used by the texture sampler.
void setMaxLOD (int lod) noexcept
Sets the maximum allowed level-of-detail parameter used by the texture sampler.
void disableComparison () noexcept
Disables the use of depth comparison.
void setComparisonMode (Compare op) noexcept
Enables the use of depth comparison and sets the depth comparison operator of the texture sampler.
void setWrap (Wrap wrap) noexcept
Sets the wrapping used for by the texture sampler.
void setBorderColor (RGBAF color) noexcept
Sets the border color of the texture sampler (used when Wrap::BORDER_CLAMP is in use).
void setLabel (std::string_view label) noexcept
Sets the debug label of the texture.
Detailed Description
One-dimensional array texture.
Constructor & Destructor Documentation
ArrayTexture1D() [1/2]
tr::ArrayTexture1D::ArrayTexture1D (int size, int layers, bool mipmapped = false, TextureFormat format = TextureFormat::RGBA8)
Allocates an uninitialized 1D array texture.
Exception Safety
Strong exception guarantee.
Exceptions
TextureBadAlloc If allocating the texture fails.
Parameters
[in] size The size of the texture in texels.
[in] layers The number of layers in the texture.
[in] mipmapped Whether the texture will be mipmapped.
[in] format The internal format of the texture.
ArrayTexture1D() [2/2]
tr::ArrayTexture1D::ArrayTexture1D (SubBitmap bitmap, bool mipmapped = false, TextureFormat format = TextureFormat::RGBA8)
Constructs a 1D array texture with data uploaded from a bitmap.
Exception Safety
Strong exception guarantee.
Exceptions
TextureBadAlloc If allocating the texture fails.
Parameters
[in] bitmap The bitmap data.
[in] mipmapped Whether the texture will be mipmapped.
[in] format The internal format of the texture.
Member Function Documentation
size()
int tr::ArrayTexture1D::size () const noexcept
Gets the size of the texture.
Returns
The size of the texture in texels.
Referenced by ArrayTexture1D().
layers()
int tr::ArrayTexture1D::layers () const noexcept
Gets the number of layers in the texture.
Returns
The number of layers in the texture.
Referenced by ArrayTexture1D(), and layers().
setRegion()
void tr::ArrayTexture1D::setRegion (glm::ivec2 tl, SubBitmap bitmap) noexcept
Sets a region of the texture as if it were a 2D texture.
Precondition
The region must fully be inside the bounds of the texture.
Parameters
[in] tl The top-left corner of the region within the texture.
[in] bitmap The bitmap data to set the region to.
Referenced by setRegion().