/**
 * @file tr.hpp
 * @brief Includes the trlib library
 */

#pragma once
#include "angle.hpp"
#include "audio_buffer.hpp"
#include "audio_context.hpp"
#include "audio_device.hpp"
#include "audio_source.hpp"
#include "audio_stream.hpp"
#include "benchmark.hpp"
#include "bitmap_format.hpp"
#include "bitmap.hpp"
#include "chrono.hpp"
#include "color.hpp"
#include "color_cast.hpp"
#include "concepts.hpp"
#include "display.hpp"
#include "draw_geometry.hpp"
#include "event.hpp"
#include "framebuffer.hpp"
#include "function.hpp"
#include "geometry.hpp"
#include "gl_context.hpp"
#include "handle.hpp"
#include "hashmap.hpp"
#include "index_buffer.hpp"
#include "iostream.hpp"
#include "keyboard.hpp"
#include "listener.hpp"
#include "mouse.hpp"
#include "norm_cast.hpp"
#include "path.hpp"
#include "bitmap_format.hpp"
#include "ranges.hpp"
#include "renderbuffer.hpp"
#include "sampler.hpp"
#include "sdl.hpp"
#include "shader_buffer.hpp"
#include "shader.hpp"
#include "shader_pipeline.hpp"
#include "texture_unit.hpp"
#include "texture.hpp"
#include "ttfont.hpp"
#include "utf8.hpp"
#include "vertex_buffer.hpp"
#include "vertex_format.hpp"
#include "vertex.hpp"
#include "window.hpp"