#pragma once
#include "angle.hpp"             // IWYU pragma: export
#include "audio_buffer.hpp"      // IWYU pragma: export
#include "audio_source.hpp"      // IWYU pragma: export
#include "audio_system.hpp"      // IWYU pragma: export
#include "benchmark.hpp"         // IWYU pragma: export
#include "bitmap.hpp"            // IWYU pragma: export
#include "bitmap_format.hpp"     // IWYU pragma: export
#include "bitmap_iterators.hpp"  // IWYU pragma: export
#include "chrono.hpp"            // IWYU pragma: export
#include "color.hpp"             // IWYU pragma: export
#include "color_cast.hpp"        // IWYU pragma: export
#include "concepts.hpp"          // IWYU pragma: export
#include "display.hpp"           // IWYU pragma: export
#include "draw_geometry.hpp"     // IWYU pragma: export
#include "event.hpp"             // IWYU pragma: export
#include "framebuffer.hpp"       // IWYU pragma: export
#include "geometry.hpp"          // IWYU pragma: export
#include "graphics_context.hpp"  // IWYU pragma: export
#include "handle.hpp"            // IWYU pragma: export
#include "hashmap.hpp"           // IWYU pragma: export
#include "index_buffer.hpp"      // IWYU pragma: export
#include "iostream.hpp"          // IWYU pragma: export
#include "keyboard.hpp"          // IWYU pragma: export
#include "listener.hpp"          // IWYU pragma: export
#include "mouse.hpp"             // IWYU pragma: export
#include "norm_cast.hpp"         // IWYU pragma: export
#include "overloaded_lambda.hpp" // IWYU pragma: export
#include "path.hpp"              // IWYU pragma: export
#include "ranges.hpp"            // IWYU pragma: export
#include "rng.hpp"               // IWYU pragma: export
#include "sdl.hpp"               // IWYU pragma: export
#include "shader.hpp"            // IWYU pragma: export
#include "shader_buffer.hpp"     // IWYU pragma: export
#include "shader_pipeline.hpp"   // IWYU pragma: export
#include "stopwatch.hpp"         // IWYU pragma: export
#include "texture.hpp"           // IWYU pragma: export
#include "texture_unit.hpp"      // IWYU pragma: export
#include "timer.hpp"             // IWYU pragma: export
#include "ttfont.hpp"            // IWYU pragma: export
#include "utf8.hpp"              // IWYU pragma: export
#include "vertex.hpp"            // IWYU pragma: export
#include "vertex_buffer.hpp"     // IWYU pragma: export
#include "vertex_format.hpp"     // IWYU pragma: export
#include "window.hpp"            // IWYU pragma: export

/// Namespace containing all libtr functionality.
namespace tr {
}